/* Mundos Sombrios — Evolução Gradual V2.10.0
 * UX canônica: Ficha | Evolução | Histórico · Sucessos habilitam · PEG efetiva.
 */
(function(){
  'use strict';
  const legacy=window.MS_PROGRESSION||{};
  const backend=()=>window.MS_EVOLUTION_BACKEND;
  const svc=()=>window.MS_SERVICES;
  const byId=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
  const unwrap=v=>v&&typeof v==='object'&&Object.prototype.hasOwnProperty.call(v,'data')?v.data:v;
  const uid=()=>String(window.currentUser?.authUserId||window.currentUser?.auth_user_id||window.currentUser?.id||'');
  const role=()=>String(window.currentUser?.role||'jogador').toLowerCase();
  const tableCtx=()=>window.msGetCurrentTableContext?.()||{table:null,asGM:false};
  let current=null,developmentContext=null,savePatched=false,leavePatched=false;
  const labelType=t=>backend()?.typeLabel?.(t)||String(t||'CAPACIDADE').toUpperCase();
  function toast(msg,type='info'){window.MS_PLATFORM?.toast?.(msg,type)}
  function err(error){return String(error?.message||error||'Operação indisponível.').replace(/^Error:\s*/,'').replace('EVOLUTION_NOT_READY','A trilha ainda não possui sucessos/requisitos suficientes.').replace('REQUIREMENTS_PENDING','Ainda existem requisitos narrativos pendentes.').replace('INSUFFICIENT_CHARACTER_PROGRESSION','PEG insuficiente para esta evolução.').replace('UPGRADE_ALREADY_PENDING','Esta evolução já está aguardando decisão do Mestre.').replace('TRACK_NOT_FOUND','A trilha de evolução não foi encontrada.').replace('REASON_REQUIRED','Informe uma justificativa.')}
  async function characterRow(target,options={}){
    if(typeof target==='object'&&target){if(target.payload)return target;return{id:target.id||target.sourceCharId,user_id:target.userId||target.participantUserId,payload:target}}
    if(typeof target==='string'&&svc()?.Characters?.view){try{return await svc().Characters.view(target,options.tableId||null)}catch(_){return{id:target,payload:options.fallback||{id:target}}}}
    return{id:String(target||''),payload:options.fallback||{}};
  }
  async function resolveTableId(charId,payload,options={}){
    if(options.tableId)return String(options.tableId);
    if(payload?.progression?.lastTableId)return String(payload.progression.lastTableId);
    try{const rows=unwrap(await svc()?.Games?.listMine?.())||[];const match=rows.find(t=>String(t.my_character_id||t.character_id||'')===String(charId));if(match?.id)return String(match.id)}catch(_){}
    return null;
  }
  function ownCharacter(row,payload){return String(row?.user_id||payload?.userId||payload?.participantUserId||payload?.ownerId||'')===uid()}
  function rankName(track){return`${Number(track.current_rank||0)} → ${Number(track.current_rank||0)+1}`}
  function requirementState(track){const req=track.requirements||[];return req.length?req.every(x=>x.done===true):true}
  function progressPct(track){const need=Math.max(1,Number(track.successes_required||10)),got=Math.min(need,Number(track.successes||0));return Math.round(got/need*100)}
  function pendingFor(state,track){return (state.upgradeRequests||[]).find(x=>x.track_id===track.id&&x.status==='pending')}
  function costOf(row,track){return backend()?.costFor?.(row,track.capability_type,Number(track.current_rank||0)+1)||Math.max(10,(Number(track.current_rank||0)+1)*10)}
  function trackCard(row,state,track){
    const own=!!state.isOwner,manager=!!state.canManage,acc=state.account||{},cost=costOf(row,track),readySuccess=Number(track.successes||0)>=Number(track.successes_required||0),reqOK=requirementState(track),enough=Number(acc.balance||0)>=cost,pending=pendingFor(state,track),ready=readySuccess&&reqOK;
    const reasons=[];if(!readySuccess)reasons.push(`${Math.max(0,Number(track.successes_required||0)-Number(track.successes||0))} sucessos restantes`);if(!reqOK)reasons.push('requisitos narrativos pendentes');if(!enough)reasons.push(`faltam ${Math.max(0,cost-Number(acc.balance||0))} PEG`);
    const req=(track.requirements||[]).map(x=>`<button type="button" class="ms-evo-req ${x.done?'done':''}" ${manager?`data-evo-req="${esc(track.capability_type)}|${esc(track.capability_key)}|${esc(x.key)}|${x.done?'0':'1'}"`: 'disabled'} title="${manager?'Alternar requisito':'Requisito definido pelo Mestre'}">${x.done?'✓':'○'} ${esc(x.label)}</button>`).join('');
    const ownerActions=own?`<button type="button" data-evo-evidence="${esc(track.capability_type)}|${esc(track.capability_key)}">REGISTRAR PRÁTICA</button><button type="button" data-evo-train="${esc(track.capability_type)}|${esc(track.capability_key)}">TREINAR</button><button type="button" class="primary" data-evo-upgrade="${esc(track.capability_type)}|${esc(track.capability_key)}" ${ready&&enough&&!pending?'':'disabled'}>${pending?'AGUARDANDO MESTRE':'SOLICITAR EVOLUÇÃO'}</button>`:'';
    const managerActions=manager?`<button type="button" data-evo-success="${esc(track.capability_type)}|${esc(track.capability_key)}">+ SUCESSOS</button><button type="button" class="danger" data-evo-accelerate="${esc(track.capability_type)}|${esc(track.capability_key)}">ACELERAR</button>`:'';
    const riskCount=Number(track.metadata?.risk_count||0),riskLabel=track.metadata?.risk_label||(String(track.metadata?.mode||'').toLowerCase()==='ocultatun'?'Ruptura do Véu':'Pressão do Gene Êxodo'),riskHint=track.metadata?.last_risk_consequence||track.metadata?.risk_profile?.consequence||'';
    const risk=['power','ritual'].includes(track.capability_type)?`<span class="${riskCount>0?'warn':''}" ${riskHint?`title="${esc(riskHint)}"`:''}>${esc(riskLabel)} <b>${riskCount}</b></span>`:'';
    return `<article class="ms-evo-track ${ready?'ready':''}" data-track-id="${esc(track.id)}"><header><div><small>${esc(labelType(track.capability_type))}</small><h4>${esc(track.label)}</h4></div><strong>${esc(rankName(track))}</strong></header><div class="ms-evo-progress"><span style="width:${progressPct(track)}%"></span></div><div class="ms-evo-track-meta"><span><b>${Number(track.successes||0)}/${Number(track.successes_required||0)}</b> sucessos</span><span>Custo recomendado <b>${cost} PEG</b></span>${risk}${ready?'<span class="ok">PRONTO</span>':''}</div>${req?`<div class="ms-evo-requirements">${req}</div>`:''}${reasons.length&&!pending?`<p class="ms-evo-hint">${esc(reasons.join(' · '))}</p>`:''}<footer>${ownerActions}${managerActions}</footer></article>`;
  }
  function groupTracks(row,state){
    const order=['attribute','skill','advantage','talent','power','ritual','class','other'],tracks=state.tracks||[];
    return order.map(type=>{const list=tracks.filter(t=>(backend()?.typeMap?.(t.capability_type)||t.capability_type)===type);if(!list.length)return'';return `<section class="ms-evo-group"><div class="ms-evo-group-head"><div><small>${esc(labelType(type))}</small><h3>${type==='attribute'?'Atributos':type==='skill'?'Perícias':type==='advantage'?'Vantagens':type==='talent'?'Talentos':type==='class'?'Classe e Cargo':'Poderes e Manifestações'}</h3></div>${state.isOwner&&['power','skill'].includes(type)?`<button type="button" data-evo-develop="${type}">DESENVOLVER</button>`:''}</div><div class="ms-evo-track-grid">${list.map(t=>trackCard(row,state,t)).join('')}</div></section>`}).join('');
  }
  function historyRows(state){
    const events=state.events||[];if(!events.length)return'<div class="ms-evo-empty">Nenhum acontecimento de evolução registrado nesta campanha.</div>';
    const label={SCENE_SUCCESS:'PRÁTICA',GM_SUCCESS:'MESTRE',TRAINING_SUCCESS:'TREINO ✓',TRAINING_FAILURE:'TREINO ✕',EVOLUTION_APPLIED:'EVOLUÇÃO',ACCELERATION:'ACELERAÇÃO',REQUIREMENT_UPDATED:'REQUISITO',DEVELOPMENT_APPROVED:'DESENVOLVIMENTO'};
    return `<div class="ms-evo-timeline">${events.map(e=>{const tr=(state.tracks||[]).find(t=>t.id===e.track_id);return`<article><span class="ms-evo-event-mark"></span><div><small>${esc(label[e.event_type]||e.event_type)} · ${new Date(e.created_at||Date.now()).toLocaleString('pt-BR')}</small><h4>${esc(tr?.label||e.metadata?.label||'Evolução')}</h4><p>${esc(e.note||e.session_label||'Registro sistêmico.')}</p><div>${Number(e.successes||0)>0?`+${Number(e.successes)} sucessos`:''}${e.metadata?.cost!=null?` · ${Number(e.metadata.cost)} PEG`:''}${e.metadata?.consequence?` · ${esc(e.metadata.consequence)}`:''}</div></div></article>`}).join('')}</div>`;
  }
  function textFromHtml(value){
    const box=document.createElement('div');box.innerHTML=String(value||'');return String(box.textContent||'').replace(/\s+/g,' ').trim();
  }
  function readList(title,items,formatter){
    if(!items?.length)return'';return `<section class="ms-viewer-section"><small>${esc(title)}</small><div class="ms-evo-sheet-list">${items.map((item,i)=>`<article>${formatter(item,i)}</article>`).join('')}</div></section>`;
  }
  function baseSheet(payload){
    const stats=[['FOR','for'],['VIG','vig'],['AGI','agi'],['INT','int'],['PRN','prn'],['PRE','pre']],resources=payload.resources&&typeof payload.resources==='object'?payload.resources:{},concept=payload.concept||{};
    const skills=Array.isArray(payload.skills)&&payload.skills.length?payload.skills:(payload.skillsHtml||[]).map(raw=>({name:textFromHtml(raw)}));
    const powers=Array.isArray(payload.powers)?payload.powers:[];
    const rituals=Array.isArray(payload.rituals)?payload.rituals.filter(x=>x?.known!==false):[];
    const equipment=Array.isArray(payload.equipment)?payload.equipment:[];
    const specific=payload.specificData&&typeof payload.specificData==='object'?Object.entries(payload.specificData).filter(([,v])=>v!==''&&v!=null&&v!==false):[];
    let out=`<section class="ms-viewer-section"><small>ATRIBUTOS</small><div class="ms-viewer-grid">${stats.map(([l,k])=>`<article class="ms-view-stat"><span>${l}</span><strong>${esc(payload?.stats?.[k]??payload?.derived?.[k]??'—')}</strong></article>`).join('')}</div></section><section class="ms-viewer-section"><small>RECURSOS E LIMITES</small><div class="ms-viewer-grid">${Object.entries(resources).map(([k,v])=>`<article class="ms-view-resource"><span>${esc(k)}</span><strong>${esc(v)}</strong></article>`).join('')||'<p>Sem recursos registrados.</p>'}</div></section>`;
    out+=readList('PERÍCIAS · VANTAGENS · TALENTOS',skills,(x)=>{const name=x?.name||x?.label||textFromHtml(x);const grade=x?.grade||x?.rank;return`<b>${esc(name||'Registro')}</b>${grade?`<span>Grau ${esc(grade)}</span>`:''}`});
    out+=readList('PODERES · PRODÍGIOS · ESCRIPTAS · POTÊNCIAS',powers,(x)=>`<b>${esc(x?.name||x?.label||x?.id||'Poder')}</b><span>${esc(x?.description||x?.effect||x?.type||'')} ${x?.progressionRank?`· Domínio ${esc(x.progressionRank)}`:''}</span>`);
    out+=readList('RITUAIS',rituals,(x)=>`<b>${esc(x?.name||x?.id||'Ritual')}</b><span>${esc(x?.description||x?.effect||'')} ${x?.progressionRank?`· Domínio ${esc(x.progressionRank)}`:''}</span>`);
    out+=readList('EQUIPAMENTOS',equipment,(x)=>`<b>${esc(x?.name||x?.label||x?.item||'Item')}</b><span>${esc(x?.description||x?.details||x?.quantity||'')}</span>`);
    if(specific.length)out+=`<section class="ms-viewer-section"><small>DADOS ESPECÍFICOS</small><div class="ms-evo-sheet-list">${specific.map(([k,v])=>`<article><b>${esc(String(k).replace(/^char-|^specific-/,'').replace(/-/g,' '))}</b><span>${esc(Array.isArray(v)?v.join(', '):typeof v==='object'?JSON.stringify(v):v)}</span></article>`).join('')}</div></section>`;
    out+=`<section class="ms-viewer-section"><small>IDENTIDADE</small><h3>${esc(concept.occupation||concept.origin||'Registro de personagem')}</h3><div class="ms-evo-sheet-narrative">${[['Origem',concept.origin],['Ocupação',concept.occupation],['Instituição',concept.institution],['Status',concept.status],['Vínculos',concept.bonds],['Motivação',concept.motivation],['Relação com o mundo',concept.worldRelation]].filter(([,v])=>v).map(([k,v])=>`<p><b>${esc(k)}:</b> ${esc(v)}</p>`).join('')||'<p>Nenhuma informação narrativa adicional registrada.</p>'}</div></section>`;
    return out;
  }

  function renderEnhancedViewer(row,state,options){
    const modal=byId('ms-character-viewer');if(!modal)return;const payload=row?.payload||{},body=modal.querySelector('[data-view-body]'),balance=Number(state?.account?.balance||0),focus=options?.focus==='evolution'?'evolution':options?.focus==='history'?'history':'sheet';
    const head=modal.querySelector('[data-view-meta]');if(head)head.textContent=[payload.category,payload.nature,payload.className||row.class_name].filter(Boolean).join(' · ');
    body.innerHTML=`<nav class="ms-evo-view-tabs"><button data-evo-tab="sheet" class="${focus==='sheet'?'active':''}">FICHA</button><button data-evo-tab="evolution" class="${focus==='evolution'?'active':''}">EVOLUÇÃO <span>${balance} PEG</span></button><button data-evo-tab="history" class="${focus==='history'?'active':''}">HISTÓRICO</button></nav><section data-evo-pane="sheet" ${focus==='sheet'?'':'hidden'}>${baseSheet(payload)}</section><section data-evo-pane="evolution" ${focus==='evolution'?'':'hidden'}><div class="ms-evo-wallet"><div><small>CONTA DE EVOLUÇÃO</small><strong>${balance} PEG</strong><span>${Number(state?.account?.lifetime_granted||0)} concedidos · ${Number(state?.account?.lifetime_spent||0)} gastos</span></div><p>Sucessos habilitam a evolução. PEG efetiva a mudança após validação da Mesa.</p></div>${!state?'<div class="ms-evo-empty">Esta ficha ainda não está vinculada a uma Mesa com Evolução Gradual.</div>':groupTracks(row,state)}</section><section data-evo-pane="history" ${focus==='history'?'':'hidden'}>${state?historyRows(state):'<div class="ms-evo-empty">Sem campanha vinculada para exibir histórico.</div>'}</section>`;
    bindViewer(body,row,state,options);
  }
  function splitData(value){const [type,key,...rest]=String(value||'').split('|');return{type,key,rest}}
  function bindViewer(root,row,state,options){
    root.querySelectorAll('[data-evo-tab]').forEach(b=>b.onclick=()=>{root.querySelectorAll('[data-evo-tab]').forEach(x=>x.classList.toggle('active',x===b));root.querySelectorAll('[data-evo-pane]').forEach(p=>p.hidden=p.dataset.evoPane!==b.dataset.evoTab)});
    if(!state)return;
    root.querySelectorAll('[data-evo-evidence]').forEach(b=>b.onclick=()=>openEvidence(row,state,splitData(b.dataset.evoEvidence)));
    root.querySelectorAll('[data-evo-train]').forEach(b=>b.onclick=()=>openTraining(row,state,splitData(b.dataset.evoTrain)));
    root.querySelectorAll('[data-evo-upgrade]').forEach(b=>b.onclick=()=>requestUpgrade(row,state,splitData(b.dataset.evoUpgrade)));
    root.querySelectorAll('[data-evo-success]').forEach(b=>b.onclick=()=>managerSuccess(row,state,splitData(b.dataset.evoSuccess)));
    root.querySelectorAll('[data-evo-accelerate]').forEach(b=>b.onclick=()=>managerAcceleration(row,state,splitData(b.dataset.evoAccelerate)));
    root.querySelectorAll('[data-evo-req]').forEach(b=>b.onclick=()=>{const d=splitData(b.dataset.evoReq);toggleRequirement(row,state,d.type,d.key,d.rest[0],d.rest[1]==='1')});
    root.querySelectorAll('[data-evo-develop]').forEach(b=>b.onclick=()=>openDevelopment(row,state,b.dataset.evoDevelop));
  }
  function ensureActionDialog(){let m=byId('ms-evo-action-dialog');if(m)return m;m=document.createElement('div');m.id='ms-evo-action-dialog';m.className='ms-evo-action-dialog';m.innerHTML='<section><header><div><small>EVOLUÇÃO GRADUAL</small><h3 data-evo-dialog-title>Ação</h3></div><button type="button" data-evo-dialog-close>×</button></header><div data-evo-dialog-body></div></section>';document.body.appendChild(m);m.querySelector('[data-evo-dialog-close]').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')};return m}
  function dialog(title,html,onSubmit){const m=ensureActionDialog(),body=m.querySelector('[data-evo-dialog-body]');m.querySelector('[data-evo-dialog-title]').textContent=title;body.innerHTML=html;m.classList.add('open');body.querySelector('[data-submit]')?.addEventListener('click',async()=>{const btn=body.querySelector('[data-submit]');btn.disabled=true;try{await onSubmit(body);m.classList.remove('open')}catch(error){toast(err(error),'error');btn.disabled=false}})}
  async function reload(row,state,focus='evolution'){try{const next=await backend().state(state.table_id,row.id);current={row,state:next,options:{...(current?.options||{}),tableId:state.table_id,focus}};renderEnhancedViewer(row,next,current.options);try{await legacy.refreshTableState?.(state.table_id)}catch(_){}}catch(error){toast(err(error),'error')}}
  function openEvidence(row,state,d){const track=state.tracks.find(t=>t.capability_type===d.type&&t.capability_key===d.key);dialog(`Registrar prática · ${track?.label||''}`,`<div class="ms-evo-form"><label>Sessão / marco<input data-session placeholder="Sessão 07 — A Queda"></label><label>Sucessos relevantes<input data-successes type="number" min="1" max="10" value="1"></label><label class="wide">O que aconteceu<textarea data-note placeholder="Ação bem-sucedida, impacto narrativo e contexto."></textarea></label><button class="primary wide" data-submit>ENVIAR AO MESTRE</button></div>`,async b=>{const n=Number(b.querySelector('[data-successes]').value||0),session=b.querySelector('[data-session]').value.trim(),note=b.querySelector('[data-note]').value.trim();if(!n||!note)throw new Error('Informe sucessos e descreva a prática.');await backend().submitEvidence(state.table_id,row.id,d.type,d.key,n,session,note);toast('Prática enviada para reconhecimento do Mestre.','success');await reload(row,state)})}
  function openTraining(row,state,d){const track=state.tracks.find(t=>t.capability_type===d.type&&t.capability_key===d.key);dialog(`Treinar · ${track?.label||''}`,`<div class="ms-evo-form"><label>Tipo de treino<select data-kind><option value="basic">Básico · CD 13 · +1</option><option value="practical" selected>Prático · CD 18 · +2</option><option value="difficult">Difícil · CD 23 · +3</option></select></label><label>Ambiente<select data-env><option value="0">Normal · +0</option><option value="2">Excelente / mentor · +2</option><option value="-2">Improvisado · -2</option></select></label><label>Período narrativo<input data-session placeholder="Dia 3 entre missões"></label><label class="wide">Contexto do treino<textarea data-note placeholder="Onde, como e com quais recursos será realizado."></textarea></label><p class="wide ms-evo-hint">O Mestre aprova o contexto. A rolagem é registrada pelo sistema. Máximo de 3 sucessos de treino por período narrativo.</p><button class="primary wide" data-submit>SOLICITAR TREINO</button></div>`,async b=>{const kind=b.querySelector('[data-kind]').value,env=Number(b.querySelector('[data-env]').value||0),session=b.querySelector('[data-session]').value.trim(),note=b.querySelector('[data-note]').value.trim();if(!session||!note)throw new Error('Informe período narrativo e contexto do treino.');await backend().requestTraining(state.table_id,row.id,d.type,d.key,kind,env,session,note);toast('Treino enviado para aprovação do Mestre.','success');await reload(row,state)})}
  async function requestUpgrade(row,state,d){const track=state.tracks.find(t=>t.capability_type===d.type&&t.capability_key===d.key);try{await backend().requestUpgrade(state.table_id,row.id,d.type,d.key,`Evolução de ${track?.label||d.key}`);toast('Evolução enviada ao Mestre. A ficha só mudará após aprovação.','success');await reload(row,state)}catch(error){toast(err(error),'error')}}
  function managerSuccess(row,state,d){const track=state.tracks.find(t=>t.capability_type===d.type&&t.capability_key===d.key);dialog(`Reconhecer sucessos · ${track?.label||''}`,`<div class="ms-evo-form"><label>Sucessos<input data-successes type="number" min="1" max="20" value="1"></label><label>Sessão / marco<input data-session placeholder="Sessão atual"></label><label class="wide">Justificativa<textarea data-note placeholder="Feito reconhecido pelo Mestre."></textarea></label><button class="primary wide" data-submit>REGISTRAR SUCESSOS</button></div>`,async b=>{const n=Number(b.querySelector('[data-successes]').value||0),session=b.querySelector('[data-session]').value.trim(),note=b.querySelector('[data-note]').value.trim();if(!n||!note)throw new Error('Informe sucessos e justificativa.');await backend().recordSuccess(state.table_id,row.id,d.type,d.key,n,session,note);toast('Sucessos incorporados à trilha.','success');await reload(row,state)})}
  function managerAcceleration(row,state,d){const track=state.tracks.find(t=>t.capability_type===d.type&&t.capability_key===d.key);dialog(`Aceleração · ${track?.label||''}`,`<div class="ms-evo-form"><label class="wide">Acontecimento excepcional<textarea data-note placeholder="Desafio mortal, sacrifício, conhecimento proibido ou despertar extraordinário."></textarea></label><label class="ms-evo-check wide"><input type="checkbox" data-free> Conceder como exceção sem consumir PEG do personagem</label><p class="wide ms-evo-hint">A aceleração ignora sucessos e requisitos da trilha e fica destacada no Ledger.</p><button class="danger wide" data-submit>ACELERAR +1 GRADUAÇÃO</button></div>`,async b=>{const note=b.querySelector('[data-note]').value.trim(),free=b.querySelector('[data-free]').checked;if(!note)throw new Error('Justifique a aceleração narrativa.');await backend().accelerate(state.table_id,row.id,d.type,d.key,free,note);toast('Aceleração aplicada e registrada.','success');await reload(row,state)})}
  async function toggleRequirement(row,state,type,key,reqKey,done){const track=state.tracks.find(t=>t.capability_type===type&&t.capability_key===key),req=track?.requirements?.find(x=>x.key===reqKey);try{await backend().setRequirement(state.table_id,row.id,type,key,reqKey,done,req?.label||reqKey);toast(done?'Requisito reconhecido.':'Requisito reaberto.','success');await reload(row,state)}catch(error){toast(err(error),'error')}}
  function openDevelopment(row,state,focus){if(!state.isOwner)return;developmentContext={tableId:state.table_id,characterId:row.id,focusType:focus,balance:Number(state.account?.balance||0),sourcePayload:clone(row.payload||{})};window.MS_FEATURES?.ensureBuilder?.().then(()=>{const chars=window.msGetCurrentCharacters?.()||[],i=chars.findIndex(x=>String(x.id)===String(row.id));if(i<0)throw new Error('A ficha precisa estar disponível na conta do jogador.');byId('ms-character-viewer')?.classList.remove('open');window.loadCharacterToBuilder?.(i,chars,false);setTimeout(()=>prepareDevelopmentBuilder(focus),100)}).catch(e=>toast(err(e),'error'))}
  function prepareDevelopmentBuilder(focus){patchBuilderSave();patchLeaveBuilder();const form=byId('char-form');if(!form)return;byId('ms-development-banner')?.remove();const banner=document.createElement('div');banner.id='ms-development-banner';banner.className='ms-progression-builder-banner';banner.innerHTML=`<b>DESENVOLVIMENTO FOCADO · ${focus==='power'?'PODER / RITUAL':'PERÍCIA / VANTAGEM'}</b><br>Somente este módulo será enviado ao Mestre. A ficha inteira não será substituída.`;form.prepend(banner);const all=['btn-tab-identity','btn-tab-stats','btn-tab-skills','btn-tab-evolution','btn-tab-powers','btn-tab-equipment','btn-tab-specific','btn-tab-rituals'];for(const id of all){const el=byId(id);if(el)el.dataset.evoOriginalDisplay=el.style.display||''}const allowed=focus==='power'?new Set(['btn-tab-powers','btn-tab-rituals']):new Set(['btn-tab-skills']);for(const id of all){const el=byId(id);if(el&&!allowed.has(id))el.style.display='none'}window.openTab?.(focus==='power'?'tab-powers':'tab-skills');const save=byId('btn-final-save');if(save)save.textContent='ENVIAR DESENVOLVIMENTO AO MESTRE'}
  function restoreBuilder(){byId('ms-development-banner')?.remove();document.querySelectorAll('[data-evo-original-display]').forEach(el=>{el.style.display=el.dataset.evoOriginalDisplay||'';delete el.dataset.evoOriginalDisplay});const save=byId('btn-final-save');if(save)save.textContent='SALVAR PERSONAGEM'}
  function patchBuilderSave(){if(savePatched||typeof window.saveCharacter!=='function')return;savePatched=true;const original=window.saveCharacter;window.saveCharacter=async function(event){if(!developmentContext)return original.apply(this,arguments);event?.preventDefault?.();try{const payload=window.buildCharacterPayloadFromBuilder?.();if(!payload)throw new Error('Não foi possível preparar o desenvolvimento.');const defaultCost=developmentContext.focusType==='power'?20:20,cost=Number(prompt(`Saldo ${developmentContext.balance} PEG. Custo solicitado ao Mestre:`,String(defaultCost))||0);if(cost<=0){toast('O desenvolvimento precisa de um custo de PEG maior que zero.','error');return false;}const note=String(prompt('Descreva a descoberta, treino, revelação ou marco que fundamenta este desenvolvimento:','Desenvolvimento narrativo')||'').trim();if(!note)return false;await backend().submitDevelopment(developmentContext.tableId,developmentContext.characterId,developmentContext.focusType,payload,cost,note);toast('Desenvolvimento enviado ao Mestre.','success');developmentContext=null;restoreBuilder();window.leaveBuilder?.();return true}catch(error){toast(err(error),'error');return false}}}
  function patchLeaveBuilder(){if(leavePatched||typeof window.leaveBuilder!=='function')return;leavePatched=true;const original=window.leaveBuilder;window.leaveBuilder=function(){developmentContext=null;restoreBuilder();return original.apply(this,arguments)}}
  function patchLegacyEvolutionTab(){const auth=byId('evolution-authorized');if(auth)auth.closest('.ms-check-row')?.remove();const panel=byId('tab-evolution')?.querySelector('.ms-section-heading p');if(panel)panel.textContent='Este registro interno permanece como memória da ficha. Sucessos válidos de campanha, treinos, requisitos e gastos de PEG são controlados pela Ficha Rápida → EVOLUÇÃO e pela Central Operacional do Mestre.';const btn=byId('tab-evolution')?.querySelector('button[onclick="addEvolutionEntry()"]');if(btn)btn.textContent='REGISTRAR ANOTAÇÃO LEGADA'}
  async function openViewer(target,options={}){
    await legacy.openViewer?.(target,options);const row=await characterRow(target,options),payload=row?.payload||{},tableId=await resolveTableId(row?.id||payload?.id,payload,options);let state=null;
    if(tableId&&backend()){try{state=await backend().state(tableId,row.id||payload.id)}catch(error){console.warn('[Mundos Sombrios] trilhas de evolução:',error)}}
    current={row,state,options:{...options,tableId}};renderEnhancedViewer(row,state,current.options);return true;
  }
  async function openEvolutionForCharacter(characterId,tableId){return openViewer(characterId,{tableId,source:'evolution-center',focus:'evolution'})}
  function init(){patchBuilderSave();patchLeaveBuilder();patchLegacyEvolutionTab();window.MS_PLATFORM?.on?.('builder:extensions-ready',()=>{patchBuilderSave();patchLeaveBuilder();patchLegacyEvolutionTab()});}
  const api=Object.freeze({...legacy,version:'2.10.0',openViewer,openEvolutionForCharacter,backend:backend(),reloadCurrent:async()=>{if(current?.state)await reload(current.row,current.state,current.options?.focus||'evolution')}});
  window.MS_PROGRESSION=api;
  window.MS_EVOLUTION=api;
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
