/* Fichas na Mesa: janela de participantes e atalhos móveis, sem estado de ficha duplicado. */
(function(){
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const context=()=>window.msGetCurrentTableContext?.()||{};
const idOf=p=>String(p.sourceCharId||p.id||'');
const nodes=new Map();let host=null,scope='',epoch=0,positions={};
function visiblePlayers(c,user){return (c.players||[]).filter(p=>!p.isNPC&&idOf(p)&&(c.asGM||p.isMe||[p.participantUserId,p.userId,p.sourceOwnerId,p.ownerId].some(id=>id!=null&&[user?.id,user?.authUserId].filter(Boolean).map(String).includes(String(id)))));}
function clamp(x,y,w=64,h=64){const top=document.body.dataset.msEnvironment==='local'||document.body.dataset.msEnvironment==='unavailable'?48:8;return {x:Math.max(8,Math.min(Number(x)||8,Math.max(8,innerWidth-w-8))),y:Math.max(top,Math.min(Number(y)||top,Math.max(top,innerHeight-h-8)))};}
function store(){try{sessionStorage.setItem('ms-sheet-positions:'+scope,JSON.stringify(positions));}catch(_){}}
function move(el,key,x,y){const p=clamp(x,y,el.offsetWidth||64,el.offsetHeight||64);el.style.left=p.x+'px';el.style.top=p.y+'px';positions[key]=p;return p;}
function draggable(el,handle,key,onClick){let drag=null,suppress=false;
 handle.addEventListener('pointerdown',e=>{if(e.button!==0)return;const r=el.getBoundingClientRect();drag={id:e.pointerId,x:e.clientX,y:e.clientY,left:r.left,top:r.top,moved:false};handle.setPointerCapture?.(e.pointerId);});
 handle.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>5)drag.moved=true;if(drag.moved){move(el,key,drag.left+dx,drag.top+dy);e.preventDefault();}});
 const end=e=>{if(!drag||e.pointerId!==drag.id)return;suppress=drag.moved;if(drag.moved)store();drag=null;};
 handle.addEventListener('pointerup',end);handle.addEventListener('pointercancel',end);
 handle.addEventListener('click',e=>{if(suppress){suppress=false;e.preventDefault();return;}onClick?.();});
 handle.addEventListener('keydown',e=>{const d={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]}[e.key];if(!e.altKey||!d)return;e.preventDefault();const r=el.getBoundingClientRect();move(el,key,r.left+d[0],r.top+d[1]);store();});
}
function ensure(){if(host)return host;host=document.createElement('div');host.id='ms-sheet-floats';host.setAttribute('aria-label','Fichas flutuantes da mesa');document.body.appendChild(host);return host;}
function closeMini(entry){entry.panel.hidden=true;entry.button.setAttribute('aria-expanded','false');}
async function toggle(entry){if(!entry.panel.hidden){closeMini(entry);return;}entry.panel.hidden=false;entry.button.setAttribute('aria-expanded','true');const r=entry.button.getBoundingClientRect();const saved=positions['panel:'+entry.id];move(entry.panel,'panel:'+entry.id,saved?.x??r.right+12,saved?.y??r.top);await fill(entry);}
async function fill(entry){const ticket=++entry.ticket,gen=epoch,c=context();entry.body.innerHTML='<p role="status">Carregando ficha…</p>';
 try{await window.MS_FEATURES.ensureProgression();const response=await window.MS_SERVICES.Characters.view(entry.id,c.table.id);const row=response?.data!==undefined?response.data:response;if(!row||response?.error)throw new Error(response?.error?.message||'Ficha indisponível para esta conta.');
 if(gen!==epoch||ticket!==entry.ticket||!visiblePlayers(context(),window.currentUser).some(p=>idOf(p)===entry.id))return;
 entry.body.innerHTML=window.MS_PROGRESSION.renderSheet(row.payload||row);const bounds=entry.panel.getBoundingClientRect();move(entry.panel,'panel:'+entry.id,bounds.left,bounds.top);entry.panel.querySelector('[data-full]').onclick=()=>window.msOpenCharacterViewer?.(entry.id,{tableId:c.table.id,source:'floating-sheet'});
 }catch(e){if(gen===epoch&&ticket===entry.ticket){entry.body.innerHTML=`<p role="alert">${esc(e?.message||'Não foi possível consultar a ficha.')}</p><button type="button" data-retry>Tentar novamente</button>`;entry.body.querySelector('[data-retry]').onclick=()=>fill(entry);}}
}
function add(player,index){const id=idOf(player),button=document.createElement('button'),panel=document.createElement('section');button.type='button';button.className='ms-sheet-orb';button.setAttribute('aria-expanded','false');button.title='Clique para abrir/recolher. Arraste para mover. Alt + setas também move.';
 panel.className='ms-sheet-mini';panel.id='ms-sheet-mini-'+encodeURIComponent(id);panel.hidden=true;panel.setAttribute('role','region');button.setAttribute('aria-controls',panel.id);
 panel.innerHTML='<header><button class="ms-sheet-drag" type="button" title="Arraste ou use Alt + setas">⠿ <span></span></button><button data-close type="button" aria-label="Recolher ficha">×</button></header><p class="ms-sheet-private">SOMENTE SUA VISUALIZAÇÃO · LEITURA</p><div class="ms-sheet-mini-body"></div><footer><button data-refresh type="button">Atualizar</button><button data-full type="button">Abrir ficha completa</button></footer>';
 const entry={id,button,panel,body:panel.querySelector('.ms-sheet-mini-body'),ticket:0};nodes.set(id,entry);ensure().append(button,panel);panel.querySelector('[data-close]').onclick=()=>{closeMini(entry);button.focus();};panel.querySelector('[data-refresh]').onclick=()=>fill(entry);
 draggable(button,button,'orb:'+id,()=>toggle(entry));draggable(panel,panel.querySelector('.ms-sheet-drag'),'panel:'+id);
 const saved=positions['orb:'+id];move(button,'orb:'+id,saved?.x??(innerWidth-90-(Math.floor(index/5)*82)),saved?.y??(150+(index%5)*76));return entry;
}
function reset(){epoch++;nodes.clear();host?.remove();host=null;document.getElementById('ms-participant-window')?.remove();scope='';}
function sync(){const c=context(),active=!!document.getElementById('screen-vtt')?.classList.contains('active');
 if(!c.table?.id||!window.currentUser){reset();return;}
 const key=String(window.currentUser.id)+':'+String(c.table.id)+':'+String(c.asGM);
 if(scope!==key){reset();scope=key;try{positions=JSON.parse(sessionStorage.getItem('ms-sheet-positions:'+scope)||'{}');}catch(_){positions={};}if(!positions||typeof positions!=='object'||Array.isArray(positions))positions={};}
 const root=ensure();root.hidden=!active;const rosterWindow=document.getElementById('ms-participant-window');if(!active&&rosterWindow)rosterWindow.hidden=true;
 const players=visiblePlayers(c,window.currentUser),ids=new Set(players.map(idOf));for(const [id,entry] of nodes){if(!ids.has(id)){entry.ticket++;entry.button.remove();entry.panel.remove();nodes.delete(id);}}
 players.forEach((p,i)=>{const entry=nodes.get(idOf(p))||add(p,i);entry.button.textContent=String(p.name||'Ficha').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();entry.button.title=(p.name||'Personagem')+' · Clique para abrir/recolher. Arraste ou use Alt + setas para mover.';entry.button.setAttribute('aria-label',`${p.name||'Personagem'}: abrir ou recolher miniatura`);entry.panel.setAttribute('aria-label','Miniatura de '+(p.name||'personagem'));entry.panel.querySelector('.ms-sheet-drag span').textContent=p.name||'Personagem';});
 if(rosterWindow&&!rosterWindow.hidden)renderParticipants(rosterWindow);
}
function renderParticipants(win){const players=visiblePlayers(context(),window.currentUser),body=win.querySelector('main');body.innerHTML=players.length?`<div class="ms-participant-grid">${players.map(p=>`<article><span class="ms-participant-seal" aria-hidden="true">${esc(String(p.name||'?').slice(0,1))}</span><h3>${esc(p.name||'Personagem')}</h3><p>${esc([p.mode,p.nature,p.className].filter(Boolean).join(' · '))}</p><dl>${Object.entries(p.isRosterOnly?{}:p.resources||{}).slice(0,4).map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl><button type="button" data-mini="${esc(idOf(p))}">Abrir / recolher miniatura</button></article>`).join('')}</div>`:'<p>Nenhuma ficha disponível nesta mesa.</p>';body.querySelectorAll('[data-mini]').forEach(b=>b.onclick=()=>{const entry=nodes.get(b.dataset.mini);if(entry)toggle(entry);});}
function openParticipants(){sync();if(!host||host.hidden)return;let win=document.getElementById('ms-participant-window');if(!win){win=document.createElement('section');win.id='ms-participant-window';win.className='ms-participant-window';win.setAttribute('role','dialog');win.setAttribute('aria-modal','false');win.setAttribute('aria-label','Fichas dos participantes');win.innerHTML='<header><button class="ms-sheet-drag" type="button">⠿ Fichas dos participantes</button><button data-close type="button" aria-label="Fechar participantes">×</button></header><p>Abra miniaturas sem sair do mapa. Os ícones podem ser arrastados e clicados novamente para recolher.</p><main></main><footer><button data-refresh type="button">Atualizar participantes</button><button data-reset type="button">Organizar ícones</button></footer>';document.body.appendChild(win);win.querySelector('[data-close]').onclick=()=>{win.hidden=true;};win.querySelector('[data-refresh]').onclick=async()=>{await window.MS_FEATURES.ensureOperational();await window.msRefreshCurrentVttRoster?.();sync();};win.querySelector('[data-reset]').onclick=()=>{let i=0;for(const entry of nodes.values()){move(entry.button,'orb:'+entry.id,innerWidth-90-Math.floor(i/5)*82,150+(i%5)*76);i++;}store();};draggable(win,win.querySelector('.ms-sheet-drag'),'window');}
 win.hidden=false;renderParticipants(win);const saved=positions.window;move(win,'window',saved?.x??80,saved?.y??110);win.querySelector('[data-close]').focus();}
function init(){const screen=document.getElementById('screen-vtt');if(screen&&typeof MutationObserver==='function')new MutationObserver(sync).observe(screen,{attributes:true,attributeFilter:['class']});const bus=window.MS_PLATFORM;for(const event of ['vtt:entered','table:roster-refreshed','table:cache-updated'])bus?.on?.(event,sync);bus?.on?.('vtt:left',reset);window.addEventListener('ms-auth-state',e=>{reset();if(e.detail?.event!=='SIGNED_OUT')queueMicrotask(sync);});window.addEventListener('screen:changing',()=>queueMicrotask(sync));window.addEventListener('resize',()=>{for(const entry of nodes.values()){for(const [el,key] of [[entry.button,'orb:'+entry.id],[entry.panel,'panel:'+entry.id]]){if(el.hidden)continue;const r=el.getBoundingClientRect();move(el,key,r.left,r.top);}}const win=document.getElementById('ms-participant-window');if(win&&!win.hidden){const r=win.getBoundingClientRect();move(win,'window',r.left,r.top);}});document.addEventListener('keydown',e=>{if(e.key!=='Escape'||document.querySelector('dialog[open]'))return;for(const entry of nodes.values())closeMini(entry);const win=document.getElementById('ms-participant-window');if(win)win.hidden=true;});sync();}
window.MS_TABLE_SHEETS=Object.freeze({openParticipants,sync,visiblePlayers,clamp});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
