/* Mundos Sombrios — Offline Data/Auth Adapter v2.10.1
 * Replica local do contrato MS_DB para QA sem Supabase/GitHub.
 * Dados ficam exclusivamente no localStorage do navegador.
 */
(function(){
  'use strict';
  const runtime=window.MS_RUNTIME_CONFIG||{};
  const sandbox=runtime.sandboxMode===true || new URLSearchParams(location.search).get('sandbox')==='1';
  const namespace=String(runtime.storageNamespace || (sandbox?'ms-sandbox-v2101':'ms-local-v2100'));
  const KEY=`${namespace}:database`;
  const SESSION=`${namespace}:session`;
  const channelName=`${namespace}:realtime`;
  const channel=typeof BroadcastChannel==='function'?new BroadcastChannel(channelName):null;
  const listeners=new Map();
  const now=()=>new Date().toISOString();
  const id=(prefix='id')=>`${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,9)}`;
  const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
  const ok=data=>({data:clone(data),error:null});
  const fail=(message,code)=>{const error=new Error(message);if(code)error.code=code;return {data:null,error};};
  const roleOf=u=>String(u?.role||'jogador').toLowerCase();
  const safeUser=u=>u?{id:u.id,email:u.email,user_metadata:{username:u.username},username:u.username,role:u.role}:null;

  function demoCharacter({id:cid,userId,name,mode='exodo',category='Combatente',nature='Nexo Padrão (Livro Base)',className='Combatente',level=3}){
    const ocult=mode==='ocultatun';
    return {id:cid,owner_id:userId,user_id:userId,name,mode,nature,class_name:className,created_at:now(),updated_at:now(),payload:{
      id:cid,ownerId:userId,userId,name,mode,category,nature,className,
      concept:{occupation:ocult?'Agente de campo':'Operador independente',motivation:'Registro de teste do sandbox integral.'},
      stats:{for:ocult?3:4,vig:3,agi:3,int:2,prn:2,pre:1},
      derived:{pv:40,defense:15,fortitude:3,reflexes:3,will:2},
      resources:ocult?{PV:40,Estamina:15,Estresse:0,Decadência:0}:{PV:40,'CÊ':40,CR:0,Estresse:0,Assimilação:0},
      skills:[
        {type:'Perícia',name:'Luta',grade:2},
        {type:'Vantagem',name:'Iniciativa Rápida',grade:1},
        {type:'Talento',name:ocult?'Condução Ritual':'Atirador',grade:1}
      ],
      skillsHtml:[
        '<div class="list-item-header"><input type="text" value="Perícia: Luta (G2)" readonly></div>',
        '<div class="list-item-header"><input type="text" value="Vantagem: Iniciativa Rápida (G1)" readonly></div>',
        `<div class="list-item-header"><input type="text" value="Talento: ${ocult?'Condução Ritual':'Atirador'} (G1)" readonly></div>`
      ],
      powers:[{id:ocult?'power-eco-velado':'power-estigma-cinetico',name:ocult?'Eco Velado':'Estigma Cinético',effect:ocult?'Manifestação controlada de um eco ritual.':'Conversão do impulso Ê em força cinética.',progressionRank:1,components:[]}],
      progression:ocult?{locked:true,existenceLevel:level,patamar:1,maxAttribute:4,classRank:1}:{locked:true,campaignTier:'veterano',campaignScale:'Veterano',maxAttribute:5,classRank:1},
      createdAt:now(),updatedAt:now()
    }};
  }

  function seed(){
    const users=[
      {id:'u-player',auth_user_id:'u-player',username:'jogador',email:'jogador@offline.local',password:'jogador123',role:'jogador',status:'active',banned:false,created_at:now(),data:{}},
      {id:'u-master',auth_user_id:'u-master',username:'mestre',email:'mestre@offline.local',password:'mestre1234',role:'mestre',status:'active',banned:false,created_at:now(),data:{}},
      {id:'u-admin',auth_user_id:'u-admin',username:'admin',email:'admin@offline.local',password:'admin12345',role:'admin',status:'active',banned:false,created_at:now(),data:{}}
    ];
    const ex=demoCharacter({id:'char-player-exodo',userId:'u-player',name:'Nexo de Teste',mode:'exodo',category:'Combatente',className:'Combatente'});
    const oc=demoCharacter({id:'char-player-ocultatun',userId:'u-player',name:'Agente de Teste',mode:'ocultatun',category:'Especialista',nature:'Agente Designado (Ocultatun)',className:'Taumatúrgico'});
    const gm=demoCharacter({id:'char-master-exodo',userId:'u-master',name:'Sentinela do Mestre',mode:'exodo',category:'Especialista',className:'Especialista'});
    const table={id:'table-sandbox-001',code:'QA2811',name:'Fenda Integral de Teste',theme:'cosmic',game_mode:'exodo',owner_id:'u-master',status:'active',visibility:'public',description:'Mesa local usada para testar Jogador, Mestre e ADM.',recruitment_mode:'open',settings:{description:'Mesa local usada para testar Jogador, Mestre e ADM.',progressionEnabled:true,recruitment:{published:true,acceptingRequests:true,maxPlayers:6,allowedExpansions:[],allowedClasses:[],sheetVisibility:'full',levelRules:{exodoMin:'iniciado',exodoMax:'veterano',existenceMin:5,existenceMax:0,patamarMin:1,patamarMax:4}}},created_at:now(),updated_at:now(),last_seen_at:now()};
    return {
      schema:3,users,characters:[ex,oc,gm],tables:[table],members:[
        {id:'mem-master',table_id:table.id,user_id:'u-master',role:'owner',status:'active',character_id:'char-master-exodo'},
        {id:'mem-player',table_id:table.id,user_id:'u-player',role:'player',status:'active',character_id:'char-player-exodo'}
      ],adminRequests:[],joinRequests:[],recruitmentInvites:[],tableInvites:[],tableStates:{[table.id]:{schemaVersion:3,scene:{},grid:{},controls:{chatLocked:false,npcHealthPublic:true,paused:false},gallery:[],chat:[],dice:[],initiative:{active:false,round:0,turn:0,order:[]}}},tableEvents:[],eventSeq:0,
      campaigns:[],sessions:[],gmNotes:[],gmNpcs:[],gmFiles:[],characterVersions:[],siteContent:{},posts:[],mapPoints:[],globalEconomy:{},
      soul:{catalog:null,accounts:{'u-player':{balance:25000,harvest:null,entitlements:[],transactions:[]},'u-master':{balance:500000,harvest:null,entitlements:[],transactions:[]},'u-admin':{balance:9999999,harvest:null,entitlements:[],transactions:[]}}},
      progression:{wallets:{[table.id]:{table_id:table.id,balance:120,lifetime_purchased:0,lifetime_distributed:0,lifetime_admin_granted:120,updated_at:now()}},accounts:{[`${table.id}:char-player-exodo`]:{table_id:table.id,character_id:'char-player-exodo',user_id:'u-player',balance:12,lifetime_granted:12,lifetime_spent:0,career_progress:0,updated_at:now()}},transactions:[],proposals:[],resourceRequests:[],tracks:{},events:[],evidenceRequests:[],trainingRequests:[],upgradeRequests:[]}
    };
  }
  function load(){try{const raw=localStorage.getItem(KEY);const state=raw?JSON.parse(raw):seed();if(!raw)localStorage.setItem(KEY,JSON.stringify(state));return state}catch(_){return seed()}}
  let state=load();
  function save(){localStorage.setItem(KEY,JSON.stringify(state));window.dispatchEvent(new CustomEvent('ms:offline-data',{detail:{namespace}}));}
  function reset(){state=seed();localStorage.setItem(KEY,JSON.stringify(state));localStorage.removeItem(SESSION);emit('RESET',{at:now()});return clone(state)}
  function currentId(){return localStorage.getItem(SESSION)||''}
  function currentProfile(){return state.users.find(u=>u.id===currentId())||null}
  function requireUser(){const u=currentProfile();if(!u)throw Object.assign(new Error('Sessão ausente.'),{code:'AUTH_REQUIRED'});return u}
  function isAdmin(){return roleOf(currentProfile())==='admin'}
  function canManage(tableId){const u=currentProfile();if(!u)return false;if(roleOf(u)==='admin')return true;const t=state.tables.find(x=>x.id===String(tableId));if(t&&String(t.owner_id)===String(u.id))return true;return state.members.some(m=>m.table_id===String(tableId)&&m.user_id===u.id&&m.status==='active'&&['owner','gm','mestre','co_mestre'].includes(String(m.role).toLowerCase()))}
  function canAccess(tableId){const u=currentProfile();return !!u&&(canManage(tableId)||isActiveMember(tableId,u.id))}
  function emit(type,payload){const msg={type,payload:clone(payload),at:Date.now()};channel?.postMessage(msg);window.dispatchEvent(new CustomEvent('ms:offline-broadcast',{detail:msg}));dispatchLocal(msg)}
  function dispatchLocal(msg){const tableId=msg.payload?.table_id||msg.payload?.tableId;for(const [key,set] of listeners.entries()){if(tableId&&key!=='*'&&key!==String(tableId))continue;for(const fn of set)try{fn(msg)}catch(_){}}}
  channel?.addEventListener('message',e=>dispatchLocal(e.data||{}));
  function subscribeRaw(tableId,fn){const key=String(tableId);if(!listeners.has(key))listeners.set(key,new Set());listeners.get(key).add(fn);return()=>listeners.get(key)?.delete(fn)}
  function charRow(c){return clone(c)}
  function tableSummary(t,u){const mem=state.members.find(m=>m.table_id===t.id&&m.user_id===u.id&&m.status==='active');return {...clone(t),active_members:state.members.filter(m=>m.table_id===t.id&&m.status==='active').length,my_member_role:mem?.role||null,my_character_id:mem?.character_id||null,is_owner:String(t.owner_id)===String(u.id)} }
  function getChar(cid){return state.characters.find(c=>String(c.id)===String(cid))||null}
  function narrativeMerge(base,incoming,name){
    const out=clone(base||{}),src=incoming||{};
    out.name=String(name||src.name||out.name||'Personagem');
    if(Object.prototype.hasOwnProperty.call(src,'avatar'))out.avatar=clone(src.avatar);
    if(Object.prototype.hasOwnProperty.call(src,'gallery'))out.gallery=clone(src.gallery);
    if(Object.prototype.hasOwnProperty.call(src,'concept'))out.concept=clone(src.concept);
    out.updatedAt=now();
    return out;
  }
  function isActiveMember(tableId,userId,characterId=null){
    return state.members.some(m=>String(m.table_id)===String(tableId)&&String(m.user_id)===String(userId)&&m.status==='active'&&(characterId==null||String(m.character_id)===String(characterId)));
  }
  function recruitmentOf(t){
    const rec=clone(t?.settings?.recruitment||t?.recruitment||{});
    rec.published=rec.published!==false;rec.acceptingRequests=rec.acceptingRequests!==false;
    rec.maxPlayers=Math.max(1,Math.min(20,Number(rec.maxPlayers||6)));
    rec.allowedExpansions=Array.isArray(rec.allowedExpansions)?rec.allowedExpansions:[];
    rec.allowedClasses=Array.isArray(rec.allowedClasses)?rec.allowedClasses:[];
    rec.sheetVisibility=['full','summary','private'].includes(String(rec.sheetVisibility))?String(rec.sheetVisibility):'summary';
    rec.levelRules={exodoMin:'iniciado',exodoMax:'veterano',existenceMin:5,existenceMax:0,patamarMin:1,patamarMax:4,...(rec.levelRules||{})};
    return rec;
  }
  function tierValue(v){return ({iniciado:1,adaptado:2,veterano:3})[String(v||'iniciado').toLowerCase()]||1}
  function tableJoinRejection(tableId,userId,characterId,{allowAlreadyMember=false}={}){
    const t=state.tables.find(x=>String(x.id)===String(tableId));if(!t)return 'TABLE_NOT_FOUND';
    if(!['active','paused'].includes(String(t.status)))return 'TABLE_NOT_AVAILABLE';
    const existing=state.members.find(m=>String(m.table_id)===String(tableId)&&String(m.user_id)===String(userId));
    if(existing?.status==='banned')return 'MEMBER_BANNED';
    if(existing?.status==='active'&&!allowAlreadyMember)return 'ALREADY_MEMBER';
    const c=getChar(characterId);if(!c||String(c.user_id)!==String(userId))return 'CHARACTER_NOT_OWNED';
    const rec=recruitmentOf(t),mode=String(t.game_mode||'exodo').toLowerCase(),cmode=String(c.mode||'').toLowerCase();
    if(mode!=='hybrid'&&cmode!==mode)return 'GAME_MODE_MISMATCH';
    if(mode==='hybrid'&&!['exodo','ocultatun'].includes(cmode))return 'GAME_MODE_MISMATCH';
    if(rec.allowedExpansions.length&&!rec.allowedExpansions.includes(String(c.nature||'')))return 'EXPANSION_MISMATCH';
    if(rec.allowedClasses.length&&!rec.allowedClasses.includes(String(c.class_name||'')))return 'CLASS_MISMATCH';
    const rules=rec.levelRules||{};
    if(cmode==='exodo'){
      const tier=tierValue(c.payload?.progression?.campaignTier||c.payload?.progression?.campaignScale);
      if(tier<tierValue(rules.exodoMin)||tier>tierValue(rules.exodoMax))return 'CHARACTER_LEVEL_MISMATCH';
    }else{
      const lvl=Number(c.payload?.progression?.existenceLevel??5),pat=Number(c.payload?.progression?.patamar??1);
      const emin=Number(rules.existenceMin??5),emax=Number(rules.existenceMax??0),pmin=Number(rules.patamarMin??1),pmax=Number(rules.patamarMax??4);
      if(lvl>emin||lvl<emax||pat<pmin||pat>pmax)return 'CHARACTER_LEVEL_MISMATCH';
    }
    const count=state.members.filter(m=>String(m.table_id)===String(tableId)&&m.status==='active'&&String(m.role).toLowerCase()==='player').length;
    if(!existing?.status&&count>=rec.maxPlayers)return 'TABLE_FULL';
    return null;
  }
  function requireReason(reason){return String(reason||'').trim()||null}
  function ensureProgressionWallet(tableId){const p=state.progression;const key=String(tableId);p.wallets[key]??={table_id:key,balance:0,lifetime_purchased:0,lifetime_distributed:0,lifetime_admin_granted:0,updated_at:now()};return p.wallets[key]}
  function ensureProgressionAccount(tableId,characterId){const c=getChar(characterId);if(!c)throw new Error('CHARACTER_NOT_FOUND');const key=`${tableId}:${characterId}`;state.progression.accounts[key]??={table_id:String(tableId),character_id:String(characterId),user_id:c.user_id,balance:0,lifetime_granted:0,lifetime_spent:0,career_progress:0,updated_at:now()};return state.progression.accounts[key]}
  function tx(data){const row={id:state.progression.transactions.length+1,created_at:now(),actor_id:currentId(),...clone(data)};state.progression.transactions.unshift(row);return row}
  function soulAccount(profileId=currentId()){state.soul.accounts[profileId]??={balance:0,harvest:null,entitlements:[],transactions:[]};return state.soul.accounts[profileId]}
  const soulCatalog=[
    {product_key:'character_slot',product_type:'character_slot',display_name:'Slot adicional de ficha',price:20000,entitlement_key:'character_slot_bonus'},
    {product_key:'master_table_slot',product_type:'table_slot',display_name:'Slot adicional de mesa',price:70000,entitlement_key:'table_slot_bonus'},
    {product_key:'exp_aprimorador',product_type:'expansion',display_name:'Aprimorador',price:50000,entitlement_key:'aprimorador'},
    {product_key:'exp_player',product_type:'expansion',display_name:'Projeto Player',price:55000,entitlement_key:'projeto-player'},
    {product_key:'exp_linhagem',product_type:'expansion',display_name:'Linhagem Herdada',price:60000,entitlement_key:'linhagem-herdada'},
    {product_key:'exp_envolto',product_type:'expansion',display_name:'O Envolto',price:70000,entitlement_key:'envolto'},
    {product_key:'exp_ordem',product_type:'expansion',display_name:'Ordem dos Sete',price:70000,entitlement_key:'ordem-dos-sete'}
  ];
  function soulState(profileId=currentId()){
    const u=state.users.find(x=>x.id===profileId)||{};const a=soulAccount(profileId);const ents=a.entitlements||[];
    const bonus=(type)=>ents.filter(e=>e.entitlement_type===type).reduce((n,e)=>n+Number(e.quantity||0),0);
    const r=roleOf(u);return {wallet:{balance:a.balance},harvest:a.harvest,entitlements:clone(ents),catalog:clone(soulCatalog),characterCapacity:r==='admin'?2147483647:(r==='mestre'?5:3)+bonus('character_slot_bonus'),tableCapacity:r==='admin'?2147483647:(r==='mestre'?3:0)+bonus('table_slot_bonus'),unlimitedCharacters:r==='admin',unlimitedTables:r==='admin',allExpansions:['mestre','admin'].includes(r),transactions:clone(a.transactions||[])};
  }

  const api={
    ready:true,enabled:false,offline:true,sandbox,namespace,
    async getSession(){const u=currentProfile();return {session:u?{user:safeUser(u),access_token:'offline'}:null,user:safeUser(u),error:null}},
    async signIn(identifier,password){const key=String(identifier||'').trim().toLowerCase();const u=state.users.find(x=>String(x.username).toLowerCase()===key||String(x.email).toLowerCase()===key);if(!u||String(u.password)!==String(password))return fail('Credenciais inválidas.','invalid_credentials');if(u.banned||u.status==='banned')return fail('Conta banida.','ACCOUNT_BANNED');localStorage.setItem(SESSION,u.id);window.dispatchEvent(new CustomEvent('ms-auth-state',{detail:{event:'SIGNED_IN',session:{user:safeUser(u)},user:safeUser(u)}}));return ok({user:safeUser(u),session:{user:safeUser(u)}})},
    async signOut(){localStorage.removeItem(SESSION);window.dispatchEvent(new CustomEvent('ms-auth-state',{detail:{event:'SIGNED_OUT',session:null,user:null}}));return {error:null}},
    async signUp({username,email,password,requestMaster=false}){const name=String(username||'').trim();const mail=String(email||'').trim().toLowerCase();if(state.users.some(u=>u.username.toLowerCase()===name.toLowerCase()||u.email.toLowerCase()===mail))return fail('Usuário ou e-mail já existe.','USER_EXISTS');const u={id:id('u'),auth_user_id:null,username:name,email:mail,password:String(password),role:'jogador',status:'active',banned:false,created_at:now(),data:{}};u.auth_user_id=u.id;state.users.push(u);if(requestMaster)state.adminRequests.unshift({id:id('req'),user_id:u.id,userId:u.id,username:u.username,status:'pending',created_at:now(),data:{type:'master_request'}});save();localStorage.setItem(SESSION,u.id);return ok({user:safeUser(u),session:{user:safeUser(u)}})},
    async resetPasswordForEmail(email){const u=state.users.find(x=>x.email.toLowerCase()===String(email||'').toLowerCase());if(u)u.data={...(u.data||{}),offlineRecoveryRequestedAt:now()};save();return {data:true,error:null}},
    async updatePassword(password){const u=requireUser();u.password=String(password);save();return ok({user:safeUser(u)})},
    async fetchMyProfile(){const u=currentProfile();return u?ok({...u,password:undefined}):fail('Sessão ausente.')},
    async ensureMyProfile(){const u=currentProfile();return u?ok({...u,password:undefined}):fail('Sessão ausente.')},
    async saveProfile(profile){const u=requireUser();u.username=String(profile?.username||u.username);u.email=String(profile?.email||u.email);u.data=clone(profile?.data||u.data||{});save();return {...clone(u),password:undefined}},
    async fetchUsers(){return state.users.map(u=>{const x=clone(u);delete x.password;return x})},
    async adminExists(){return state.users.some(u=>roleOf(u)==='admin'&&!u.banned)},
    async bootstrapFirstAdmin(username){const u=requireUser();if(state.users.some(x=>roleOf(x)==='admin'&&x.id!==u.id))return fail('ADMIN_ALREADY_EXISTS');u.role='admin';u.username=String(username||u.username);save();return ok({...u,password:undefined})},
    async adminSetUserRole(userId,role){if(!isAdmin())return fail('ADMIN_REQUIRED');const u=state.users.find(x=>x.id===String(userId));if(!u)return fail('USER_NOT_FOUND');u.role=['jogador','mestre','admin'].includes(String(role))?String(role):'jogador';save();return ok({...u,password:undefined})},
    async adminSetUserBanned(userId,banned){if(!isAdmin())return fail('ADMIN_REQUIRED');const u=state.users.find(x=>x.id===String(userId));if(!u)return fail('USER_NOT_FOUND');u.banned=!!banned;u.status=u.banned?'banned':'active';save();return ok({...u,password:undefined})},
    async adminUpdateUsername(userId,username){if(!isAdmin())return fail('ADMIN_REQUIRED');const u=state.users.find(x=>x.id===String(userId));if(!u)return fail('USER_NOT_FOUND');u.username=String(username||u.username);save();return ok({...u,password:undefined})},
    async syncUserState(){return {synced:false,reason:'offline-local'}},

    async fetchMyCharacters(){const u=requireUser();return ok(state.characters.filter(c=>c.user_id===u.id).map(charRow))},
    async saveCharacter(character){const u=requireUser();const cid=String(character?.id||id('char'));let row=getChar(cid);if(row&&row.user_id!==u.id&&roleOf(u)!=='admin')return fail('CHARACTER_FORBIDDEN');const payload=clone({...character,id:cid,ownerId:u.id,userId:u.id,updatedAt:now()});if(row){if(String(payload.mode||row.mode)!==String(row.mode)||String(payload.nature??row.nature)!==String(row.nature||'')||String(payload.className??row.class_name)!==String(row.class_name||''))return fail('CHARACTER_ARCHETYPE_LOCKED');state.characterVersions.push({id:id('ver'),character_id:cid,version_no:state.characterVersions.filter(v=>v.character_id===cid).length+1,payload:clone(row.payload),created_at:now()});row.name=String(payload.name||row.name);row.payload=narrativeMerge(row.payload,payload,row.name);row.updated_at=now()}else{const category=String(payload.category||payload.concept?.category||'').trim();if(!String(payload.name||'').trim())return fail('CHARACTER_NAME_REQUIRED');if(!category)return fail('CHARACTER_CATEGORY_REQUIRED');if(!String(payload.nature||'').trim())return fail('CHARACTER_EXPANSION_REQUIRED');if(!String(payload.className||'').trim())return fail('CHARACTER_CLASS_REQUIRED');payload.progression={...(payload.progression||{}),locked:true,createdInCampaign:false};row={id:cid,owner_id:u.id,user_id:u.id,name:String(payload.name),mode:payload.mode||'exodo',nature:payload.nature,class_name:payload.className,payload,created_at:now(),updated_at:now()};state.characters.push(row)}save();emit('CHARACTER_SAVED',{character_id:cid,user_id:u.id});return ok(row)},
    async deleteMyCharacter(characterId){const u=requireUser();const i=state.characters.findIndex(c=>c.id===String(characterId)&&c.user_id===u.id);if(i<0)return fail('CHARACTER_NOT_FOUND');state.characters.splice(i,1);state.members.forEach(m=>{if(m.character_id===String(characterId))m.character_id=null});save();return ok(true)},
    async fetchCharacterVersions(characterId){return ok(state.characterVersions.filter(v=>v.character_id===String(characterId)).sort((a,b)=>b.version_no-a.version_no))},
    async restoreCharacterVersion(characterId,versionId){const u=requireUser(),v=state.characterVersions.find(x=>x.id===String(versionId)&&x.character_id===String(characterId)),c=getChar(characterId);if(!v||!c)return fail('VERSION_NOT_FOUND');if(c.user_id!==u.id&&roleOf(u)!=='admin')return fail('CHARACTER_FORBIDDEN');c.payload=narrativeMerge(c.payload,v.payload,v.payload?.name||c.name);c.name=c.payload.name||c.name;c.updated_at=now();save();return ok(c)},
    async fetchCharacterView(characterId,tableId=null){const c=getChar(characterId);if(!c)return fail('CHARACTER_NOT_FOUND');const u=requireUser();let visibility='full';if(tableId){const member=isActiveMember(tableId,u.id),manager=canManage(tableId),own=String(c.user_id)===String(u.id);if(!member&&!manager&&!own)return fail('VIEW_FORBIDDEN');if(!own&&!manager&&roleOf(u)!=='admin')visibility=recruitmentOf(state.tables.find(t=>String(t.id)===String(tableId))).sheetVisibility}else if(c.user_id!==u.id&&roleOf(u)!=='admin')return fail('VIEW_FORBIDDEN');const row=clone(c);if(visibility==='private')row.payload={name:c.name,mode:c.mode,nature:c.nature,className:c.class_name,avatar:c.payload?.avatar,category:c.payload?.category||c.payload?.concept?.category};else if(visibility==='summary')row.payload={name:c.name,mode:c.mode,nature:c.nature,className:c.class_name,avatar:c.payload?.avatar,category:c.payload?.category||c.payload?.concept?.category,stats:clone(c.payload?.stats),resources:clone(c.payload?.resources),derived:clone(c.payload?.derived),progression:clone(c.payload?.progression)};row.visibility=visibility;return ok(row)},
    async updateCharacterAsGM(tableId,character){if(!canManage(tableId))return fail('GM_REQUIRED');const c=getChar(character?.id);if(!c)return fail('CHARACTER_NOT_FOUND');state.characterVersions.push({id:id('ver'),character_id:c.id,version_no:state.characterVersions.filter(v=>v.character_id===c.id).length+1,payload:clone(c.payload),created_at:now()});c.name=String(character?.name||c.name);c.payload=narrativeMerge(c.payload,character,c.name);c.updated_at=now();save();return ok(c)},

    async fetchMyTables(){const u=requireUser();const visible=roleOf(u)==='admin'?state.tables:state.tables.filter(t=>t.owner_id===u.id||state.members.some(m=>m.table_id===t.id&&m.user_id===u.id&&m.status==='active'));return ok(visible.map(t=>tableSummary(t,u)))},
    async fetchMyTableSummaries(){return this.fetchMyTables()},
    async createTableRemote(payload){const u=requireUser();if(!['mestre','admin'].includes(roleOf(u)))return fail('GM_REQUIRED');const tid=id('table'),code=String(payload?.code||Math.random().toString(36).slice(2,8)).toUpperCase(),rec=clone(payload?.recruitment||payload?.settings?.recruitment||{});const settings={...(clone(payload?.settings||{})),description:String(payload?.description||payload?.settings?.description||''),recruitment:rec};const t={id:tid,code,name:String(payload?.name||'Nova Fenda'),theme:payload?.theme||'default',game_mode:payload?.gameMode||payload?.game_mode||'exodo',owner_id:u.id,status:'active',visibility:payload?.visibility||'public',description:settings.description,recruitment_mode:payload?.recruitmentMode||'open',settings,created_at:now(),updated_at:now(),last_seen_at:now()};state.tables.push(t);state.members.push({id:id('mem'),table_id:tid,user_id:u.id,role:'owner',status:'active',character_id:null});ensureProgressionWallet(tid);save();emit('TABLE_CHANGED',{table_id:tid});return ok(t)},
    async joinTableRemote(code,characterId){const u=requireUser();let t=state.tables.find(x=>String(x.code).toUpperCase()===String(code||'').toUpperCase());let invite=null;if(!t){invite=state.tableInvites.find(x=>String(x.code).toUpperCase()===String(code||'').toUpperCase()&&x.active!==false&&(!x.expires_at||new Date(x.expires_at)>new Date())&&(!x.max_uses||x.uses<x.max_uses));if(invite)t=state.tables.find(x=>x.id===invite.table_id)}if(!t)return fail('TABLE_NOT_FOUND');const existing=state.members.find(x=>x.table_id===t.id&&x.user_id===u.id&&x.status==='active');const reason=tableJoinRejection(t.id,u.id,characterId,{allowAlreadyMember:!!existing});if(reason)return fail(reason);let m=state.members.find(x=>x.table_id===t.id&&x.user_id===u.id);if(!m){m={id:id('mem'),table_id:t.id,user_id:u.id,role:'player',status:'active',character_id:String(characterId)};state.members.push(m)}else{m.status='active';m.character_id=String(characterId);if(!['owner','gm','mestre','co_mestre'].includes(String(m.role).toLowerCase()))m.role='player'}if(invite){invite.uses=Number(invite.uses||0)+1;if(invite.max_uses>0&&invite.uses>=invite.max_uses)invite.active=false}ensureProgressionAccount(t.id,characterId);save();emit('MEMBERSHIP_CHANGED',{table_id:t.id});return ok(tableSummary(t,u))},
    async leaveTableRemote(code){const u=requireUser();const t=state.tables.find(x=>x.code.toUpperCase()===String(code||'').toUpperCase()||x.id===String(code));if(!t)return fail('TABLE_NOT_FOUND');const m=state.members.find(x=>x.table_id===t.id&&x.user_id===u.id);if(m)m.status='left';save();emit('MEMBERSHIP_CHANGED',{table_id:t.id});return ok(true)},
    async deleteTableSecure(tableId){if(!canManage(tableId))return fail('OWNER_REQUIRED');state.tables=state.tables.filter(t=>t.id!==String(tableId));state.members=state.members.filter(m=>m.table_id!==String(tableId));delete state.tableStates[String(tableId)];delete state.progression.wallets[String(tableId)];Object.keys(state.progression.accounts).filter(k=>k.startsWith(`${tableId}:`)).forEach(k=>delete state.progression.accounts[k]);save();emit('TABLE_DELETED',{table_id:String(tableId)});return ok(true)},
    async updateTableSettingsSecure(tableId,settings){if(!canManage(tableId))return fail('OWNER_REQUIRED');const t=state.tables.find(x=>x.id===String(tableId));if(!t)return fail('TABLE_NOT_FOUND');t.settings={...(t.settings||{}),...(clone(settings)||{})};t.updated_at=now();save();return ok(t)},
    async archiveTableSecure(tableId,archived=true){if(!canManage(tableId))return fail('OWNER_REQUIRED');const t=state.tables.find(x=>x.id===String(tableId));if(!t)return fail('TABLE_NOT_FOUND');t.status=archived?'archived':'active';t.updated_at=now();save();return ok(t)},
    async setTableLiveStatus(tableId,status){if(!canManage(tableId))return fail('GM_REQUIRED');const t=state.tables.find(x=>x.id===String(tableId));if(!t)return fail('TABLE_NOT_FOUND');t.status=String(status||'active');t.last_seen_at=now();save();emit('TABLE_CHANGED',{table_id:t.id});return ok(true)},
    async touchTablePresence(tableId,online=true){const u=requireUser();emit('PRESENCE',{table_id:String(tableId),user_id:u.id,username:u.username,online:!!online});return ok(true)},
    async fetchTableRoster(tableId){if(!canAccess(tableId))return fail('TABLE_ACCESS_REQUIRED');return ok(state.members.filter(m=>m.table_id===String(tableId)).map(m=>({...clone(m),profile:clone(state.users.find(u=>u.id===m.user_id)||{}),character:getChar(m.character_id)})))},
    async fetchTableCharacters(tableId){if(!canAccess(tableId))return fail('TABLE_ACCESS_REQUIRED');const ids=state.members.filter(m=>m.table_id===String(tableId)&&m.status==='active'&&m.character_id).map(m=>m.character_id);return ok(state.characters.filter(c=>ids.includes(c.id)))},
    async setTableMemberStatus(tableId,userId,status){if(!canManage(tableId))return fail('GM_REQUIRED');const m=state.members.find(x=>x.table_id===String(tableId)&&x.user_id===String(userId));if(!m)return fail('MEMBER_NOT_FOUND');m.status=String(status);save();emit('MEMBERSHIP_CHANGED',{table_id:String(tableId)});return ok(m)},
    async setTableMemberRole(tableId,userId,role){if(!canManage(tableId))return fail('GM_REQUIRED');const m=state.members.find(x=>x.table_id===String(tableId)&&x.user_id===String(userId));if(!m)return fail('MEMBER_NOT_FOUND');m.role=String(role);save();return ok(m)},
    async linkTableCharacter(tableId,characterId){const u=requireUser(),c=getChar(characterId);if(!c||c.user_id!==u.id)return fail('CHARACTER_NOT_FOUND');const existing=state.members.find(x=>x.table_id===String(tableId)&&x.user_id===u.id&&x.status==='active');if(!existing)return fail('TABLE_MEMBERSHIP_REQUIRED');const rejection=tableJoinRejection(tableId,u.id,characterId,{allowAlreadyMember:true});if(rejection)return fail(rejection);existing.character_id=c.id;ensureProgressionAccount(tableId,c.id);save();return ok(existing)},
    async createTableInvite(tableId,expiresAt,maxUses){if(!canManage(tableId))return fail('GM_REQUIRED');const inv={id:id('inv'),table_id:String(tableId),code:Math.random().toString(36).slice(2,10).toUpperCase(),expires_at:expiresAt||null,max_uses:Number(maxUses||0),uses:0,created_at:now()};state.tableInvites.push(inv);save();return ok(inv)},
    async fetchPublicTableDirectory(){const u=currentProfile();return ok(state.tables.filter(t=>t.status==='active'&&t.visibility!=='private'&&recruitmentOf(t).published).map(t=>{const rec=recruitmentOf(t),sum=u?tableSummary(t,u):clone(t),owner=state.users.find(x=>x.id===t.owner_id),rq=u?[...state.joinRequests].reverse().find(r=>r.table_id===t.id&&r.user_id===u.id):null,inv=u?state.recruitmentInvites.find(i=>i.table_id===t.id&&i.status==='pending'&&(!i.expires_at||new Date(i.expires_at)>new Date())&&(i.scope==='global'||i.target_user_id===u.id)):null;return {...sum,owner_username:owner?.username||'Mestre',description:t.settings?.description||t.description||'',allowed_expansions:clone(rec.allowedExpansions),allowed_classes:clone(rec.allowedClasses),max_players:rec.maxPlayers,player_count:state.members.filter(m=>m.table_id===t.id&&m.status==='active'&&String(m.role).toLowerCase()==='player').length,online_count:0,accepting_requests:rec.acceptingRequests,is_member:u?isActiveMember(t.id,u.id):false,request_status:rq?.status||null,request_reason:rq?.rejection_reason||null,invite_id:inv?.id||null,invite_scope:inv?.scope||null,invite_message:inv?.message||null}}))},
    async requestTableJoin(tableId,characterId){const u=requireUser(),t=state.tables.find(x=>String(x.id)===String(tableId));if(!t)return fail('TABLE_NOT_FOUND');if(!recruitmentOf(t).acceptingRequests)return fail('REQUESTS_CLOSED');if(state.joinRequests.some(r=>r.table_id===String(tableId)&&r.user_id===u.id&&r.status==='pending'))return fail('REQUEST_ALREADY_PENDING');const reason=tableJoinRejection(tableId,u.id,characterId);const r={id:id('join'),table_id:String(tableId),user_id:u.id,character_id:String(characterId||''),status:reason?'auto_rejected':'pending',rejection_reason:reason||null,created_at:now(),username:u.username,character_name:getChar(characterId)?.name||'',character_mode:getChar(characterId)?.mode||'',character_nature:getChar(characterId)?.nature||'',character_class:getChar(characterId)?.class_name||''};state.joinRequests.push(r);save();emit('JOIN_REQUEST',{table_id:String(tableId)});return ok(r)},
    async cancelTableJoinRequest(requestId){const u=requireUser();const r=state.joinRequests.find(x=>x.id===String(requestId)&&x.user_id===u.id);if(!r)return fail('REQUEST_NOT_FOUND');r.status='cancelled';save();return ok(true)},
    async fetchTableJoinRequests(tableId){if(!canManage(tableId))return fail('GM_REQUIRED');return ok(state.joinRequests.filter(r=>r.table_id===String(tableId)))},
    async resolveTableJoinRequest(requestId,approved,reason=''){const r=state.joinRequests.find(x=>x.id===String(requestId));if(!r||!canManage(r.table_id))return fail('GM_REQUIRED');if(r.status!=='pending')return ok(r);if(approved){const rejection=tableJoinRejection(r.table_id,r.user_id,r.character_id);if(rejection){r.status='auto_rejected';r.rejection_reason=rejection;r.decided_at=now();save();return ok(r)}let m=state.members.find(x=>x.table_id===r.table_id&&x.user_id===r.user_id);if(!m){m={id:id('mem'),table_id:r.table_id,user_id:r.user_id,role:'player',status:'active',character_id:r.character_id};state.members.push(m)}else{m.status='active';m.character_id=r.character_id||m.character_id}ensureProgressionAccount(r.table_id,r.character_id);r.status='approved'}else{r.status='rejected';r.rejection_reason=String(reason||'')}r.decided_at=now();save();emit('MEMBERSHIP_CHANGED',{table_id:r.table_id});return ok(r)},
    async fetchTableRecruitmentInvites(tableId){const u=requireUser();return ok(state.recruitmentInvites.filter(r=>r.table_id===String(tableId)&&(canManage(tableId)||r.target_user_id===u.id||r.scope==='global')))},
    async createTableRecruitmentInvite(tableId,scope,targetUsername,message,expiresAt){if(!canManage(tableId))return fail('GM_REQUIRED');const sc=String(scope||'global')==='user'?'user':'global',target=sc==='user'?state.users.find(u=>u.username.toLowerCase()===String(targetUsername||'').toLowerCase()):null;if(sc==='user'&&!target)return fail('USER_NOT_FOUND');const r={id:id('rinv'),table_id:String(tableId),scope:sc,target_user_id:target?.id||null,target_username:target?.username||'',message:message||'',expires_at:expiresAt||null,status:'pending',active:true,accepted_count:0,created_at:now()};state.recruitmentInvites.push(r);save();return ok(r)},
    async acceptTableRecruitmentInvite(inviteId,characterId){const u=requireUser();const r=state.recruitmentInvites.find(x=>x.id===String(inviteId)&&x.status==='pending');if(!r)return fail('INVITE_NOT_FOUND');if(r.scope==='user'&&r.target_user_id!==u.id)return fail('INVITE_FORBIDDEN');const rejection=tableJoinRejection(r.table_id,u.id,characterId);if(rejection)return fail(rejection);let m=state.members.find(x=>x.table_id===r.table_id&&x.user_id===u.id);if(!m){m={id:id('mem'),table_id:r.table_id,user_id:u.id,role:'player',status:'active',character_id:String(characterId)};state.members.push(m)}else{m.status='active';m.character_id=String(characterId)}ensureProgressionAccount(r.table_id,characterId);r.status='accepted';r.accepted_at=now();save();return ok(m)},
    async cancelTableRecruitmentInvite(inviteId){const r=state.recruitmentInvites.find(x=>x.id===String(inviteId));if(!r||!canManage(r.table_id))return fail('GM_REQUIRED');r.status='cancelled';save();return ok(true)},
    async updateTableRecruitment(tableId,mode,description,recruitment){if(!canManage(tableId))return fail('GM_REQUIRED');const t=state.tables.find(x=>x.id===String(tableId));if(!t)return fail('TABLE_NOT_FOUND');t.game_mode=String(mode||t.game_mode);t.recruitment_mode=String(mode||t.recruitment_mode);t.description=String(description||'');t.settings={...(t.settings||{}),description:t.description,recruitment:clone(recruitment||{})};t.updated_at=now();save();return ok(t)},
    async subscribeTableDirectory(onRefresh,onStatus){onStatus?.('SUBSCRIBED');const stop=subscribeRaw('*',msg=>{if(msg.type.startsWith('TABLE_')||msg.type==='MEMBERSHIP_CHANGED')onRefresh?.(msg)});return stop},

    async fetchTableState(tableId){if(!canAccess(tableId))return fail('TABLE_ACCESS_REQUIRED');return ok(clone(state.tableStates[String(tableId)]||{}))},
    async saveTableState(tableId,next){if(!canAccess(tableId))return fail('TABLE_ACCESS_REQUIRED');state.tableStates[String(tableId)]=clone(next||{});save();emit('STATE',{table_id:String(tableId),state:next});return ok(state.tableStates[String(tableId)])},
    async publishTableEvent(tableId,type,payload){const u=requireUser();if(!canAccess(tableId))return fail('TABLE_ACCESS_REQUIRED');const e={id:++state.eventSeq,table_id:String(tableId),event_type:String(type),payload:clone(payload||{}),actor_id:u.id,created_at:now()};state.tableEvents.push(e);save();emit('TABLE_EVENT',e);return ok(e)},
    async broadcastTableEvent(tableId,type,payload){const u=requireUser();if(!canAccess(tableId))return fail('TABLE_ACCESS_REQUIRED');if(String(type)==='grid_preview'&&!canManage(tableId))return fail('GM_REQUIRED');const e={id:null,table_id:String(tableId),event_type:String(type),payload:clone(payload||{}),actor_id:u.id,created_at:now(),transient:true};emit('TABLE_EVENT',e);return ok(e)},
    async fetchTableEvents(tableId){if(!canAccess(tableId))return fail('TABLE_ACCESS_REQUIRED');return ok(state.tableEvents.filter(e=>e.table_id===String(tableId)))},
    async fetchTableEventsAfter(tableId,lastId=0,limit=500){if(!canAccess(tableId))return fail('TABLE_ACCESS_REQUIRED');return ok(state.tableEvents.filter(e=>e.table_id===String(tableId)&&Number(e.id)>Number(lastId)).slice(-Number(limit||500)))},
    async subscribeTable(tableId,handlers={}){const u=requireUser();if(!canAccess(tableId))throw new Error('TABLE_ACCESS_REQUIRED');const presence={};presence[u.id]=[{user_id:u.id,username:u.username,role:u.role,online_at:now()}];handlers.presence?.(presence);handlers.status?.('SUBSCRIBED');const stop=subscribeRaw(String(tableId),msg=>{if(msg.type==='TABLE_EVENT'&&msg.payload?.table_id===String(tableId))handlers.event?.(clone(msg.payload));if(msg.type==='PRESENCE'&&msg.payload?.table_id===String(tableId)){presence[msg.payload.user_id]=msg.payload.online?[{...msg.payload,online_at:now()}]:[];handlers.presence?.(clone(presence))}});return()=>{stop();handlers.status?.('CLOSED')}},

    async createCampaign(tableId,name,description){if(!canManage(tableId))return fail('GM_REQUIRED');const c={id:id('camp'),table_id:String(tableId),name:String(name||'Campanha'),description:String(description||''),created_at:now()};state.campaigns.push(c);save();return ok(c)},
    async fetchCampaign(tableId){return ok(state.campaigns.find(c=>c.table_id===String(tableId))||null)},
    async createSession(tableId,title,campaignId){if(!canManage(tableId))return fail('GM_REQUIRED');const s={id:id('sess'),table_id:String(tableId),campaign_id:campaignId||null,title:String(title||'Sessão'),status:'open',created_at:now()};state.sessions.push(s);save();return ok(s)},
    async fetchSessions(tableId){return ok(state.sessions.filter(s=>s.table_id===String(tableId)))},
    async updateSessionStatus(sessionId,status){const s=state.sessions.find(x=>x.id===String(sessionId));if(!s||!canManage(s.table_id))return fail('GM_REQUIRED');s.status=String(status);save();return ok(s)},

    async fetchAdminRequests(){return clone(state.adminRequests)},
    async saveAdminRequest(req){state.adminRequests.unshift({...clone(req),id:String(req?.id||id('req')),created_at:req?.createdAt||now(),user_id:req?.userId||currentId()});save();return clone(state.adminRequests[0])},
    async updateAdminRequestStatus(reqId,status,data){const r=state.adminRequests.find(x=>String(x.id)===String(reqId));if(!r)return null;r.status=String(status);r.data={...(r.data||{}),...(clone(data)||{})};r.updated_at=now();save();return clone(r)},
    async resolveAdminRequestSecure(reqId,status='approved',reason=''){if(!isAdmin())return fail('ADMIN_REQUIRED');const r=state.adminRequests.find(x=>String(x.id)===String(reqId));if(!r)return fail('REQUEST_NOT_FOUND');if(String(r.status||'pending')!=='pending')return ok(r);r.status=String(status);r.reason=String(reason);r.updated_at=now();if(r.data?.type==='master_request'&&status==='approved'){const u=state.users.find(x=>x.id===r.user_id);if(u)u.role='mestre'}save();return ok(r)},
    async silenceAdminRequestSecure(reqId){if(!isAdmin())return fail('ADMIN_REQUIRED');const r=state.adminRequests.find(x=>String(x.id)===String(reqId));if(!r)return fail('REQUEST_NOT_FOUND');r.silenced=true;save();return ok(r)},
    async deleteAdminRequestSecure(reqId){if(!isAdmin())return fail('ADMIN_REQUIRED');state.adminRequests=state.adminRequests.filter(x=>String(x.id)!==String(reqId));save();return ok(true)},

    async saveGMNote(tableId,note){if(!canManage(tableId))return fail('GM_REQUIRED');const n={...clone(note),id:String(note?.id||id('note')),table_id:String(tableId),updated_at:now()};state.gmNotes=state.gmNotes.filter(x=>x.id!==n.id);state.gmNotes.unshift(n);save();return ok(n)},
    async deleteGMNote(noteId){const row=state.gmNotes.find(x=>x.id===String(noteId));if(!row||!canManage(row.table_id))return fail('GM_REQUIRED');state.gmNotes=state.gmNotes.filter(x=>x.id!==String(noteId));save();return ok(true)},
    async fetchGMNotes(tableId){return ok(state.gmNotes.filter(x=>x.table_id===String(tableId)))},
    async saveGMNpc(tableId,npc){if(!canManage(tableId))return fail('GM_REQUIRED');const n={...clone(npc),id:String(npc?.id||id('npc')),table_id:String(tableId),updated_at:now()};state.gmNpcs=state.gmNpcs.filter(x=>x.id!==n.id);state.gmNpcs.unshift(n);save();return ok(n)},
    async deleteGMNpc(npcId){const row=state.gmNpcs.find(x=>x.id===String(npcId));if(!row||!canManage(row.table_id))return fail('GM_REQUIRED');state.gmNpcs=state.gmNpcs.filter(x=>x.id!==String(npcId));save();return ok(true)},
    async fetchGMNpcs(tableId){return ok(state.gmNpcs.filter(x=>x.table_id===String(tableId)))},
    async uploadGMFile(tableId,file){if(!canManage(tableId))return fail('GM_REQUIRED');const row={id:id('file'),table_id:String(tableId),path:id('blob'),name:file?.name||'arquivo',mime_type:file?.type||'application/octet-stream',size_bytes:file?.size||0,created_at:now(),data_url:null};if(file&&typeof FileReader==='function')row.data_url=await new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>resolve(null);r.readAsDataURL(file)});state.gmFiles.unshift(row);save();return ok(row)},
    async fetchGMFiles(tableId){return ok(state.gmFiles.filter(x=>x.table_id===String(tableId)))},
    async createSignedGMFileUrl(path){const f=state.gmFiles.find(x=>x.path===String(path));return f?ok({signedUrl:f.data_url||'#'}):fail('FILE_NOT_FOUND')},
    async deleteGMFile(fileId){const row=state.gmFiles.find(x=>x.id===String(fileId));if(!row||!canManage(row.table_id))return fail('GM_REQUIRED');state.gmFiles=state.gmFiles.filter(x=>x.id!==String(fileId));save();return ok(true)},

    async fetchSiteContent(key='portal-official'){return clone(state.siteContent[String(key)]||null)},
    async saveSiteContent(content,key='portal-official'){if(!isAdmin())return null;state.siteContent[String(key)]=clone(content||{});save();return {key:String(key),content:clone(content||{}),updated_at:now()}},
    async fetchPosts(){return clone(state.posts)},
    async savePost(post){if(!isAdmin())return null;const p={...clone(post),id:String(post?.id||id('post')),updated_at:now()};state.posts=state.posts.filter(x=>x.id!==p.id);state.posts.unshift(p);save();return clone(p)},
    async deletePost(postId){if(!isAdmin())return false;state.posts=state.posts.filter(x=>x.id!==String(postId));save();return true},
    async uploadPortalMedia(file){const dataUrl=file&&typeof FileReader==='function'?await new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>resolve(null);r.readAsDataURL(file)}):null;const path=id('portal');return {id:path,path,name:file?.name||'midia',kind:String(file?.type||'').startsWith('video/')?'video':'image',type:file?.type||'',url:dataUrl||'',createdAt:now()}},
    async getPortalMediaUrl(path){return String(path||'')},
    async removePortalMedia(){return true},

    async fetchMapPoints(){return clone(state.mapPoints)},async saveMapPoints(points){state.mapPoints=clone(points||[]);save();return clone(state.mapPoints)},
    async fetchGlobalEconomy(){return clone(state.globalEconomy)},async saveGlobalEconomy(next){state.globalEconomy=clone(next||{});save();return clone(state.globalEconomy)},

    async fetchSoulAccountState(){return ok(soulState())},
    async touchSoulActivity(source='offline'){const a=soulAccount();if(!a.harvest)a.harvest={source,started_at:now(),expires_at:new Date(Date.now()+30*60000).toISOString(),earned:0};save();return ok(soulState())},
    async tickSoulHarvest(){const a=soulAccount();if(a.harvest&&Date.parse(a.harvest.expires_at)>Date.now()){a.balance+=100;a.harvest.earned=Number(a.harvest.earned||0)+100;a.transactions.unshift({id:id('soul'),tx_type:'HARVEST',amount:100,balance_after:a.balance,created_at:now()})}else a.harvest=null;save();return ok(soulState())},
    async purchaseSoulProduct(productKey){const a=soulAccount(),p=soulCatalog.find(x=>x.product_key===String(productKey));if(!p)return fail('PRODUCT_NOT_FOUND');if(a.balance<p.price)return fail('INSUFFICIENT_SOULDRAKMA');a.balance-=p.price;const type=p.product_type==='expansion'?'expansion':p.entitlement_key;let e=a.entitlements.find(x=>x.entitlement_type===type&&x.entitlement_key===p.entitlement_key);if(!e){e={entitlement_type:type,entitlement_key:p.entitlement_key,quantity:0};a.entitlements.push(e)}e.quantity+=1;a.transactions.unshift({id:id('soul'),tx_type:'PURCHASE',amount:-p.price,balance_after:a.balance,reason:p.product_key,created_at:now()});save();return ok(soulState())},
    async adminGetSoulAccount(profileId){if(!isAdmin())return fail('ADMIN_REQUIRED');return ok({...soulState(String(profileId)),profile_id:String(profileId),transactions:clone(soulAccount(String(profileId)).transactions)})},
    async adminAdjustSoulBalance(profileId,amount,reason){if(!isAdmin())return fail('ADMIN_REQUIRED');const a=soulAccount(String(profileId));a.balance=Math.max(0,a.balance+Number(amount||0));a.transactions.unshift({id:id('soul'),tx_type:'ADMIN_ADJUST',amount:Number(amount||0),balance_after:a.balance,reason:String(reason||''),created_at:now()});save();return ok(soulState(String(profileId)))},
    async adminSetSoulEntitlement(profileId,type,key,quantity,reason){if(!isAdmin())return fail('ADMIN_REQUIRED');const a=soulAccount(String(profileId));a.entitlements=a.entitlements.filter(e=>!(e.entitlement_type===String(type)&&e.entitlement_key===String(key)));if(Number(quantity)>0)a.entitlements.push({entitlement_type:String(type),entitlement_key:String(key),quantity:Number(quantity),reason:String(reason||'')});save();return ok(soulState(String(profileId)))},

    async fetchProgressionTableState(tableId){const u=requireUser(),tid=String(tableId),wallet=ensureProgressionWallet(tid),managed=canManage(tid),m=state.members.find(x=>x.table_id===tid&&x.user_id===u.id&&x.status==='active'),myAccount=m?.character_id?ensureProgressionAccount(tid,m.character_id):null,base={wallet:managed?clone(wallet):null,myAccount:clone(myAccount),accounts:managed?Object.values(state.progression.accounts).filter(a=>a.table_id===tid).map(a=>({...clone(a),name:getChar(a.character_id)?.name||'Ficha'})):[],pendingProposals:managed?state.progression.proposals.filter(p=>p.table_id===tid&&p.status==='pending'):[],resourceRequests:managed?state.progression.resourceRequests.filter(r=>r.table_id===tid&&r.status==='pending'):[],recentTransactions:managed?state.progression.transactions.filter(t=>t.table_id===tid).slice(0,20):[],config:{soul_cost_per_point:1000}};return ok(window.MS_EVOLUTION_BACKEND?.extendOfflineState?window.MS_EVOLUTION_BACKEND.extendOfflineState(tid,base):base)},
    async buyTableProgressionPoints(tableId,points){if(!canManage(tableId))return fail('GM_REQUIRED');const n=Math.max(1,Number(points||0)),a=soulAccount(),cost=n*1000;if(a.balance<cost)return fail('INSUFFICIENT_SOULDRAKMA');a.balance-=cost;const w=ensureProgressionWallet(tableId);w.balance+=n;w.lifetime_purchased+=n;w.updated_at=now();tx({table_id:String(tableId),amount:n,balance_after:w.balance,tx_type:'TABLE_PURCHASE',reason:`Compra local: ${cost} SD`});save();return ok({wallet:w,soulBalance:a.balance})},
    async grantCharacterProgression(tableId,characterId,amount,reason){if(!canManage(tableId))return fail('GM_REQUIRED');const why=requireReason(reason);if(!why)return fail('REASON_REQUIRED');const c=getChar(characterId);if(!c||!isActiveMember(tableId,c.user_id,characterId))return fail('CHARACTER_MEMBERSHIP_REQUIRED');const n=Math.max(1,Number(amount||0)),w=ensureProgressionWallet(tableId);if(w.balance<n)return fail('INSUFFICIENT_TABLE_PROGRESSION');const a=ensureProgressionAccount(tableId,characterId);w.balance-=n;w.lifetime_distributed+=n;a.balance+=n;a.lifetime_granted+=n;a.updated_at=now();const t=tx({table_id:String(tableId),character_id:String(characterId),target_user_id:a.user_id,amount:n,balance_after:a.balance,tx_type:'CHARACTER_GRANT',reason:why});save();emit('TABLE_EVENT',{id:++state.eventSeq,table_id:String(tableId),event_type:'character:evolution_granted',payload:{characterId:String(characterId),amount:n,targetUserId:a.user_id,transactionId:t.id},actor_id:currentId(),created_at:now()});return ok({wallet:w,account:a,transaction:t})},
    async recordCareerSuccess(tableId,characterId,amount,reason){if(!canManage(tableId))return fail('GM_REQUIRED');const why=requireReason(reason);if(!why)return fail('REASON_REQUIRED');const c=getChar(characterId);if(!c||!isActiveMember(tableId,c.user_id,characterId))return fail('CHARACTER_MEMBERSHIP_REQUIRED');if(String(c.mode).toLowerCase()!=='ocultatun')return fail('OCULTATUN_ONLY');const n=Math.max(1,Math.min(20,Number(amount||0))),a=ensureProgressionAccount(tableId,characterId);a.career_progress+=n;tx({table_id:String(tableId),character_id:String(characterId),amount:n,balance_after:a.balance,tx_type:'CAREER_PROGRESS',reason:why});save();return ok(a)},
    async reverseProgressionGrant(transactionId,reason=''){if(!canManage(state.progression.transactions.find(t=>String(t.id)===String(transactionId))?.table_id))return fail('GM_REQUIRED');const t=state.progression.transactions.find(x=>String(x.id)===String(transactionId)&&x.tx_type==='CHARACTER_GRANT');if(!t)return fail('GRANT_NOT_FOUND');if(state.progression.transactions.some(x=>x.tx_type==='CHARACTER_GRANT_REVERSAL'&&String(x.reference_id)===String(t.id)))return fail('ALREADY_REVERSED');const a=ensureProgressionAccount(t.table_id,t.character_id),w=ensureProgressionWallet(t.table_id);if(a.balance<Number(t.amount))return fail('POINTS_ALREADY_SPENT');a.balance-=Number(t.amount);w.balance+=Number(t.amount);w.lifetime_distributed=Math.max(0,Number(w.lifetime_distributed||0)-Number(t.amount));tx({table_id:t.table_id,character_id:t.character_id,amount:-Number(t.amount),balance_after:a.balance,tx_type:'CHARACTER_GRANT_REVERSAL',reason:String(reason||''),reference_id:String(t.id)});save();return ok({wallet:w,account:a})},
    async upgradeProgressionAttribute(){return fail('SEMANTIC_EVOLUTION_REQUIRED')},
    async submitProgressionProposal(){return fail('SEMANTIC_EVOLUTION_REQUIRED')},
    async resolveProgressionProposal(proposalId,approved,finalCost=null,reason=''){const p=state.progression.proposals.find(x=>x.id===String(proposalId));if(!p||!canManage(p.table_id))return fail('GM_REQUIRED');p.status=approved?'approved':'rejected';p.decided_at=now();p.reason=String(reason||'');if(approved){const a=ensureProgressionAccount(p.table_id,p.character_id),cost=Number(finalCost??p.requested_cost);if(a.balance<cost)return fail('INSUFFICIENT_CHARACTER_PROGRESSION');const c=getChar(p.character_id);c.payload=clone(p.proposed_payload);c.payload.progression={...(c.payload.progression||{}),lastTableId:p.table_id};c.name=c.payload.name||c.name;c.updated_at=now();a.balance-=cost;a.lifetime_spent+=cost;p.final_cost=cost;tx({table_id:p.table_id,character_id:p.character_id,amount:-cost,balance_after:a.balance,tx_type:'PROPOSAL_APPROVED',reason:p.reason,reference_id:p.id})}save();return ok({proposal:p})},
    async adjustCharacterResource(tableId,characterId,resourceKey,delta,reason){if(!canManage(tableId))return fail('GM_REQUIRED');const why=requireReason(reason);if(!why)return fail('REASON_REQUIRED');const c=getChar(characterId);if(!c)return fail('CHARACTER_NOT_FOUND');c.payload.resources=c.payload.resources||{};const key=String(resourceKey),old=Number(c.payload.resources[key]||0),next=old+Number(delta||0);c.payload.resources[key]=next;c.updated_at=now();tx({table_id:String(tableId),character_id:String(characterId),amount:Number(delta||0),balance_after:next,tx_type:'RESOURCE_ADJUST',reason:why,metadata:{resource:key}});save();return ok({character:c,resource:key,value:next})},
    async requestCharacterResource(tableId,characterId,resourceKey,delta,reason){const u=requireUser(),c=getChar(characterId);if(!c||c.user_id!==u.id||!isActiveMember(tableId,u.id,characterId))return fail('CHARACTER_MEMBERSHIP_REQUIRED');const why=requireReason(reason);if(!why)return fail('REASON_REQUIRED');const r={id:id('rreq'),table_id:String(tableId),character_id:String(characterId),user_id:u.id,resource_key:String(resourceKey),delta:Number(delta||0),reason:why,status:'pending',created_at:now()};state.progression.resourceRequests.unshift(r);save();return ok(r)},
    async resolveCharacterResourceRequest(requestId,approved){const r=state.progression.resourceRequests.find(x=>x.id===String(requestId));if(!r||!canManage(r.table_id))return fail('GM_REQUIRED');r.status=approved?'approved':'rejected';r.decided_at=now();if(approved){const result=await api.adjustCharacterResource(r.table_id,r.character_id,r.resource_key,r.delta,r.reason);if(result.error)return result}save();return ok(r)},
    async fetchProgressionAdminTables(){if(!isAdmin())return fail('ADMIN_REQUIRED');return ok(state.tables.map(t=>{const w=ensureProgressionWallet(t.id),owner=state.users.find(u=>u.id===t.owner_id),members=state.members.filter(m=>m.table_id===t.id&&m.status==='active'&&m.character_id),tracks=Object.values(state.progression?.tracks||{}).filter(x=>x.table_id===t.id),pending=[...(state.progression?.evidenceRequests||[]),...(state.progression?.trainingRequests||[]),...(state.progression?.upgradeRequests||[]),...(state.progression?.proposals||[]).filter(x=>x.proposal_kind==='development')].filter(x=>x.table_id===t.id&&x.status==='pending');return {table_id:t.id,name:t.name,table_name:t.name,game_mode:t.game_mode,status:t.status,code:t.code,owner_username:owner?.username||'',balance:w.balance,lifetime_admin_granted:w.lifetime_admin_granted,lifetime_purchased:w.lifetime_purchased,lifetime_distributed:w.lifetime_distributed,participant_count:members.length,ready_count:tracks.filter(x=>x.status==='ready').length,pending_evolution_count:pending.length}}))},
    async fetchProgressionAdminTableLedger(tableId,limit=100){if(!isAdmin())return fail('ADMIN_REQUIRED');const tid=String(tableId),table=state.tables.find(t=>String(t.id)===tid);if(!table)return fail('TABLE_NOT_FOUND');const w=ensureProgressionWallet(tid),n=Math.max(10,Math.min(200,Number(limit||100))),transactions=(state.progression?.transactions||[]).filter(x=>String(x.table_id)===tid).slice(0,n).map(x=>{const c=x.character_id?getChar(x.character_id):null,a=state.users.find(u=>u.id===x.actor_id),target=state.users.find(u=>u.id===x.target_user_id);return {...clone(x),character_name:c?.name||'',actor_username:a?.username||'',target_username:target?.username||''}}),events=(state.progression?.events||[]).filter(x=>String(x.table_id)===tid).slice(0,n).map(x=>{const c=getChar(x.character_id),track=state.progression?.tracks?.[x.track_id],a=state.users.find(u=>u.id===x.actor_id);return {...clone(x),character_name:c?.name||'',capability_label:track?.label||'',capability_type:track?.capability_type||'',actor_username:a?.username||''}});return ok({table:{table_id:tid,table_name:table.name,game_mode:table.game_mode,status:table.status,balance:w.balance,lifetime_purchased:w.lifetime_purchased,lifetime_admin_granted:w.lifetime_admin_granted,lifetime_distributed:w.lifetime_distributed},transactions,events})},
    async adminAdjustTableProgression(tableId,amount,reason){if(!isAdmin())return fail('ADMIN_REQUIRED');const why=requireReason(reason);if(!why)return fail('REASON_REQUIRED');const w=ensureProgressionWallet(tableId),n=Number(amount||0);if(w.balance+n<0)return fail('INSUFFICIENT_TABLE_PROGRESSION');w.balance+=n;if(n>0)w.lifetime_admin_granted+=n;w.updated_at=now();tx({table_id:String(tableId),amount:n,balance_after:w.balance,tx_type:'ADMIN_TABLE_ADJUST',reason:why});save();return ok(w)},

    __debug:{reset,snapshot:()=>clone(state),switchRole:async(role)=>{const u=state.users.find(x=>x.role===String(role));if(!u)throw new Error('Papel offline não encontrado.');localStorage.setItem(SESSION,u.id);window.dispatchEvent(new CustomEvent('ms-auth-state',{detail:{event:'SIGNED_IN',session:{user:safeUser(u)},user:safeUser(u)}}));return clone(u)}}
  };
  api.__evolutionContext=Object.freeze({state:()=>state,save,now,id,clone,ok,fail,currentId,currentProfile,requireUser,isAdmin,canManage,isActiveMember,getChar,ensureProgressionWallet,ensureProgressionAccount,tx,emit});
  window.MS_OFFLINE_DB={version:'2.10.4',create:()=>api,reset,snapshot:()=>clone(state),credentials:[
    {role:'jogador',username:'jogador',password:'jogador123'},
    {role:'mestre',username:'mestre',password:'mestre1234'},
    {role:'admin',username:'admin',password:'admin12345'}
  ]};
})();
