/* Mundos Sombrios — Evolução Gradual 2.10.1 · transporte + motor sandbox
 * Regra operacional: Sucessos habilitam; PEG efetiva. O servidor/adapter é a autoridade.
 */
(function(){
  'use strict';
  const db=()=>window.MS_DB;
  const ctx=()=>db()?.__evolutionContext;
  const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
  const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
  const slug=s=>norm(s).replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')||'capacidade';
  const successRequired=nextRank=>Math.max(10,Math.max(1,Number(nextRank||1))*10);
  const typeMap=v=>{const t=norm(v);if(t.includes('pericia')||t==='skill')return'skill';if(t.includes('vantagem')||t==='advantage')return'advantage';if(t.includes('talento')||t==='talent')return'talent';if(t.includes('ritual'))return'ritual';if(t.includes('poder')||t.includes('prodig')||t.includes('escrip')||t.includes('potenc')||t==='power')return'power';if(t.includes('classe')||t.includes('cargo')||t==='class')return'class';if(t.includes('atrib')||['for','vig','agi','int','prn','pre'].includes(t))return'attribute';return t||'other'};
  const typeLabel=t=>({attribute:'ATRIBUTO',skill:'PERÍCIA',advantage:'VANTAGEM',talent:'TALENTO',power:'PODER / POTÊNCIA',ritual:'RITUAL',class:'CLASSE / CARGO',other:'OUTRA CAPACIDADE'})[typeMap(t)]||String(t||'CAPACIDADE').toUpperCase();
  const classRequirements=()=>[
    {key:'narrative_milestone',label:'Marco narrativo designado pelo Mestre',done:false},
    {key:'superior_approval',label:'Aprovação de figura superior / organização',done:false},
    {key:'ideology',label:'Conduta coerente com a ideologia da classe',done:false},
    {key:'new_domain',label:'Novo domínio, ritual ou habilidade especial',done:false},
    {key:'acceptance_rite',label:'Ritual de aceitação ou provação',done:false}
  ];
  function requirementsFor(type,mode='exodo'){
    const t=typeMap(type),m=norm(mode);
    if(t==='class')return classRequirements();
    if(t==='advantage')return[{key:'narrative_justification',label:'Justificativa narrativa / social reconhecida pelo Mestre',done:false}];
    if(t==='power')return[{key:'power_breakthrough',label:m==='ocultatun'?'Ruptura, revelação ou influência sobrenatural reconhecida':'Descoberta, assimilação ou manifestação genética reconhecida',done:false}];
    if(t==='ritual')return[{key:'ritual_breakthrough',label:m==='ocultatun'?'Estudo, exposição ou ruptura ritual reconhecida':'Experimentação, exposição ou domínio ritual reconhecido',done:false}];
    return[];
  }
  const resetsNarrativeRequirements=t=>['class','advantage','power','ritual'].includes(typeMap(t));
  function riskProfile(mode,type,trainingType,riskCount=1){
    const t=typeMap(type),m=norm(mode),n=Math.max(1,Number(riskCount||1));if(!['power','ritual'].includes(t))return{};
    const severity=n>=4?'critical':n>=2?'elevated':'latent';
    return m==='ocultatun'
      ?{theme:'ruptura_ocultatun',label:'Ruptura do Véu',risk_count:n,severity,consequence:'A falha amplia a influência do oculto: o Mestre pode converter o risco em influência de entidade, manifestação/ritual involuntário, perda de sanidade ou ruptura com o normal.',master_prompt:'Resolver em cena conforme o pacto, a exposição e o preço psíquico/espiritual assumido pelo personagem.'}
      :{theme:'instabilidade_exodo',label:'Pressão do Gene Êxodo',risk_count:n,severity,consequence:'A falha amplia a instabilidade genética: o Mestre pode converter o risco em novo estigma, mutação de prodígio, assimilação não planejada ou dano ao corpo/mente.',master_prompt:'Resolver em cena conforme a manifestação do Gene Êxodo, a pressão do treino e o estado físico/mental do personagem.'};
  }
  function costFor(character,type,targetRank){
    const t=typeMap(type),rank=Math.max(1,Number(targetRank||1)),mode=norm(character?.mode||character?.payload?.mode||'exodo');
    if(t==='attribute')return mode==='ocultatun'?20*rank:10*rank;
    if(t==='skill')return 10*rank;
    if(t==='advantage'||t==='talent')return Math.max(20,10*rank);
    if(t==='power'||t==='ritual')return 20*rank;
    if(t==='class')return 30*rank;
    return 10*rank;
  }
  function ensureBuckets(state){
    state.progression=state.progression||{};
    Object.assign(state.progression,{tracks:state.progression.tracks||{},events:state.progression.events||[],evidenceRequests:state.progression.evidenceRequests||[],trainingRequests:state.progression.trainingRequests||[],upgradeRequests:state.progression.upgradeRequests||[],proposals:state.progression.proposals||[],resourceRequests:state.progression.resourceRequests||[],transactions:state.progression.transactions||[]});
    return state.progression;
  }
  function parseLegacySkills(payload){
    const structured=Array.isArray(payload?.skills)?payload.skills.map(x=>({type:String(x.type||x.kind||'Perícia'),name:String(x.name||x.label||''),grade:Math.max(1,Number(x.grade||x.rank||1))})).filter(x=>x.name):[];
    if(structured.length)return structured;
    const out=[];
    for(const raw of payload?.skillsHtml||[]){
      const text=String(raw||'').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/\s+/g,' ');
      const m=text.match(/(Per[ií]cia|Vantagem|Talento)\s*:\s*(.+?)\s*\(G\s*(\d+)\)/i);
      if(m)out.push({type:m[1],name:m[2].trim(),grade:Number(m[3])||1});
    }
    return out;
  }
  function trackKey(tableId,characterId,type,key){return`${tableId}:${characterId}:${typeMap(type)}:${slug(key)}`}
  function ensureTrack(C,tableId,characterId,type,key,label,rank=0,metadata={}){
    const state=C.state(),p=ensureBuckets(state),t=typeMap(type),k=slug(key||label),id=trackKey(tableId,characterId,t,k);
    let row=p.tracks[id];
    if(!row){const current=Math.max(0,Number(rank||0));row=p.tracks[id]={id,table_id:String(tableId),character_id:String(characterId),capability_type:t,capability_key:k,label:String(label||key||'Capacidade'),current_rank:current,successes:0,successes_required:successRequired(current+1),status:'progress',requirements:requirementsFor(t,metadata?.mode||'exodo'),metadata:{risk_count:0,discoveries:0,...clone(metadata||{})},created_at:C.now(),updated_at:C.now()};}
    else{
      row.label=String(label||row.label);row.metadata={...(row.metadata||{}),...(clone(metadata)||{})};
      if(Number(rank)>=0&&Number(row.current_rank)!==Number(rank)&&Number(row.successes||0)===0){row.current_rank=Number(rank);row.successes_required=successRequired(Number(rank)+1)}
    }
    return row;
  }
  function ensureCharacterTracks(C,tableId,characterId){
    const c=C.getChar(characterId);if(!c)return[];const p=c.payload||{},stats=p.stats||{};
    for(const [key,label] of Object.entries({for:'FOR',vig:'VIG',agi:'AGI',int:'INT',prn:'PRN',pre:'PRE'}))ensureTrack(C,tableId,characterId,'attribute',key,label,Number(stats[key]||0),{source:'stats',mode:p.mode||c.mode||'exodo'});
    for(const item of parseLegacySkills(p)){const t=typeMap(item.type);ensureTrack(C,tableId,characterId,t,item.name,item.name,item.grade,{source:'skills',originalType:item.type,mode:p.mode||c.mode||'exodo'});}
    for(const power of Array.isArray(p.powers)?p.powers:[]){const name=String(power?.name||'Poder');ensureTrack(C,tableId,characterId,'power',power?.id||name,name,Math.max(1,Number(power?.progressionRank||power?.grade||1)),{source:'powers',powerId:power?.id||null,mode:p.mode||c.mode||'exodo'});}
    for(const ritual of Array.isArray(p.rituals)?p.rituals.filter(r=>r?.known!==false):[]){const name=String(ritual?.name||ritual?.id||'Ritual');ensureTrack(C,tableId,characterId,'ritual',ritual?.id||name,name,Math.max(1,Number(ritual?.progressionRank||1)),{source:'rituals',ritualId:ritual?.id||null,mode:p.mode||c.mode||'exodo'});}
    const className=String(p.className||c.class_name||'Classe / Cargo');ensureTrack(C,tableId,characterId,'class','class',className,Math.max(1,Number(p.progression?.classRank||1)),{source:'class',className,mode:p.mode||c.mode||'exodo'});
    return Object.values(ensureBuckets(C.state()).tracks).filter(x=>x.table_id===String(tableId)&&x.character_id===String(characterId));
  }
  function ownMember(C,tableId,characterId){const u=C.requireUser(),c=C.getChar(characterId);return c&&String(c.user_id)===String(u.id)&&C.isActiveMember(tableId,u.id,characterId)}
  function manager(C,tableId){return C.canManage(tableId)}
  function account(C,tableId,characterId){return C.ensureProgressionAccount(String(tableId),String(characterId))}
  function findTrack(C,tableId,characterId,type,key){ensureCharacterTracks(C,tableId,characterId);return ensureBuckets(C.state()).tracks[trackKey(tableId,characterId,type,key)]||null}
  function addEvent(C,data){const p=ensureBuckets(C.state()),row={id:C.id('evoevt'),table_id:String(data.table_id),character_id:String(data.character_id),track_id:data.track_id||null,actor_id:C.currentId(),event_type:String(data.event_type||'NOTE'),successes:Number(data.successes||0),session_label:String(data.session_label||''),note:String(data.note||''),metadata:clone(data.metadata||{}),created_at:C.now()};p.events.unshift(row);return row}
  function allRequirementsDone(track){return (track?.requirements||[]).every(x=>x.done===true)}
  function updateTrackStatus(track){track.successes_required=successRequired(Number(track.current_rank||0)+1);track.status=Number(track.successes||0)>=Number(track.successes_required||0)&&allRequirementsDone(track)?'ready':'progress';track.updated_at=new Date().toISOString();return track}
  function addSuccess(C,track,amount,meta={}){const want=Math.max(0,Number(amount||0)),remaining=Math.max(0,Number(track.successes_required||0)-Number(track.successes||0)),applied=Math.min(want,remaining);track.successes=Number(track.successes||0)+applied;updateTrackStatus(track);addEvent(C,{table_id:track.table_id,character_id:track.character_id,track_id:track.id,event_type:meta.eventType||'SUCCESS_RECORDED',successes:applied,session_label:meta.session||'',note:meta.note||'',metadata:{requested:want,...(meta.metadata||{})}});return applied}
  function htmlSkill(type,name,grade){const safe=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));return`<div class="list-item-header"><input type="text" value="${safe(type)}: ${safe(name)} (G${Number(grade)||1})" readonly><button type="button" class="hide-on-view" onclick="this.closest('.list-item').remove()">&#10006;</button></div>`}
  function applyTrackToCharacter(C,track,targetRank){
    const c=C.getChar(track.character_id);if(!c)throw new Error('CHARACTER_NOT_FOUND');const p=c.payload||(c.payload={}),t=track.capability_type,key=track.capability_key;
    if(t==='attribute'){p.stats=p.stats||{};p.stats[key]=targetRank;}
    else if(['skill','advantage','talent'].includes(t)){
      const canonical={skill:'Perícia',advantage:'Vantagem',talent:'Talento'}[t],items=parseLegacySkills(p);let found=false;
      for(const item of items){if(typeMap(item.type)===t&&slug(item.name)===key){item.grade=targetRank;found=true}}
      if(!found)items.push({type:canonical,name:track.label,grade:targetRank});
      p.skills=items.map(x=>({type:x.type||canonical,name:x.name,grade:Number(x.grade||1)}));
      const legacy=Array.isArray(p.skillsHtml)?p.skillsHtml.slice():[];let replaced=false;
      p.skillsHtml=legacy.map(raw=>{const text=String(raw||'').replace(/<[^>]+>/g,' ');if(typeMap(text.split(':')[0])===t&&slug((text.match(/:\s*(.+?)\s*\(G/i)||[])[1]||'')===key){replaced=true;return String(raw).replace(/\(G\s*\d+\)/i,`(G${targetRank})`)}return raw});
      if(!replaced)p.skillsHtml.push(htmlSkill(canonical,track.label,targetRank));
    }else if(t==='power'){
      p.powers=Array.isArray(p.powers)?p.powers:[];const item=p.powers.find(x=>slug(x?.id||x?.name)===key||String(x?.id||'')===String(track.metadata?.powerId||''));if(item)item.progressionRank=targetRank;
    }else if(t==='ritual'){
      p.rituals=Array.isArray(p.rituals)?p.rituals:[];const item=p.rituals.find(x=>slug(x?.id||x?.name)===key||String(x?.id||'')===String(track.metadata?.ritualId||''));if(item)item.progressionRank=targetRank;
    }else if(t==='class'){p.progression={...(p.progression||{}),classRank:targetRank};}
    p.progression={...(p.progression||{}),lastTableId:String(track.table_id),lastEvolutionAt:C.now()};c.name=String(p.name||c.name);c.updated_at=C.now();return c;
  }
  function localState(C,args){
    const tableId=String(args.p_table_id||''),charId=String(args.p_character_id||''),u=C.requireUser();if(!C.canManage(tableId)&&!C.isActiveMember(tableId,u.id,charId))throw new Error('TABLE_ACCESS_REQUIRED');const tracks=ensureCharacterTracks(C,tableId,charId),p=ensureBuckets(C.state()),managed=C.canManage(tableId),own=C.getChar(charId)?.user_id===u.id;
    return {character_id:charId,table_id:tableId,tracks:clone(tracks),events:clone(p.events.filter(e=>e.table_id===tableId&&e.character_id===charId).slice(0,80)),account:clone(account(C,tableId,charId)),evidenceRequests:clone(p.evidenceRequests.filter(r=>r.table_id===tableId&&r.character_id===charId&&(managed||r.user_id===u.id))),trainingRequests:clone(p.trainingRequests.filter(r=>r.table_id===tableId&&r.character_id===charId&&(managed||r.user_id===u.id))),upgradeRequests:clone(p.upgradeRequests.filter(r=>r.table_id===tableId&&r.character_id===charId&&(managed||r.user_id===u.id))),developmentRequests:clone(p.proposals.filter(r=>r.table_id===tableId&&r.character_id===charId&&r.proposal_kind==='development'&&(managed||r.user_id===u.id))),canManage:managed,isOwner:own,trainingRules:{basic:{dc:13,successes:1},practical:{dc:18,successes:2},difficult:{dc:23,successes:3},maxSuccessesPerPeriod:3}};
  }
  function localSubmitEvidence(C,a){const tableId=String(a.p_table_id),charId=String(a.p_character_id);if(!ownMember(C,tableId,charId))throw new Error('CHARACTER_MEMBERSHIP_REQUIRED');const track=findTrack(C,tableId,charId,a.p_capability_type,a.p_capability_key);if(!track)throw new Error('TRACK_NOT_FOUND');const n=Math.max(1,Math.min(10,Number(a.p_successes||1))),p=ensureBuckets(C.state()),r={id:C.id('evidence'),table_id:tableId,character_id:charId,user_id:C.currentId(),track_id:track.id,capability_type:track.capability_type,capability_key:track.capability_key,label:track.label,successes:n,session_label:String(a.p_session_label||''),note:String(a.p_note||''),status:'pending',created_at:C.now()};p.evidenceRequests.unshift(r);C.save();return r}
  function localResolveEvidence(C,a){const p=ensureBuckets(C.state()),r=p.evidenceRequests.find(x=>x.id===String(a.p_request_id));if(!r||!manager(C,r.table_id))throw new Error('GM_REQUIRED');if(r.status!=='pending')return r;r.status=a.p_approved?'approved':'rejected';r.decided_at=C.now();r.decision_reason=String(a.p_reason||'');if(a.p_approved){const t=p.tracks[r.track_id]||findTrack(C,r.table_id,r.character_id,r.capability_type,r.capability_key);r.applied_successes=addSuccess(C,t,r.successes,{eventType:'SCENE_SUCCESS',session:r.session_label,note:r.note,metadata:{requestId:r.id,approvedBy:C.currentId()}})}C.save();return r}
  function localRecordSuccess(C,a){const tableId=String(a.p_table_id),charId=String(a.p_character_id);if(!manager(C,tableId))throw new Error('GM_REQUIRED');const t=findTrack(C,tableId,charId,a.p_capability_type,a.p_capability_key);if(!t)throw new Error('TRACK_NOT_FOUND');const applied=addSuccess(C,t,Math.max(1,Math.min(20,Number(a.p_successes||1))),{eventType:'GM_SUCCESS',session:a.p_session_label,note:a.p_note,metadata:{direct:true}});C.save();return{track:clone(t),applied_successes:applied}}
  function localRequestTraining(C,a){const tableId=String(a.p_table_id),charId=String(a.p_character_id);if(!ownMember(C,tableId,charId))throw new Error('CHARACTER_MEMBERSHIP_REQUIRED');const t=findTrack(C,tableId,charId,a.p_capability_type,a.p_capability_key);if(!t)throw new Error('TRACK_NOT_FOUND');const kind=['basic','practical','difficult'].includes(String(a.p_training_type))?String(a.p_training_type):'practical',mod=[-2,0,2].includes(Number(a.p_environment_modifier))?Number(a.p_environment_modifier):0,p=ensureBuckets(C.state()),r={id:C.id('training'),table_id:tableId,character_id:charId,user_id:C.currentId(),track_id:t.id,capability_type:t.capability_type,capability_key:t.capability_key,label:t.label,training_type:kind,environment_modifier:mod,session_label:String(a.p_session_label||''),note:String(a.p_note||''),status:'pending',created_at:C.now()};p.trainingRequests.unshift(r);C.save();return r}
  function localResolveTraining(C,a){const p=ensureBuckets(C.state()),r=p.trainingRequests.find(x=>x.id===String(a.p_request_id));if(!r||!manager(C,r.table_id))throw new Error('GM_REQUIRED');if(r.status!=='pending')return r;r.decision_reason=String(a.p_reason||'');r.decided_at=C.now();if(!a.p_approved){r.status='rejected';C.save();return r}const t=p.tracks[r.track_id]||findTrack(C,r.table_id,r.character_id,r.capability_type,r.capability_key),rules={basic:{dc:13,award:1},practical:{dc:18,award:2},difficult:{dc:23,award:3}}[r.training_type],period=r.session_label||new Date().toISOString().slice(0,10),used=p.events.filter(e=>e.track_id===t.id&&e.event_type==='TRAINING_SUCCESS'&&String(e.metadata?.period||'')===period).reduce((n,e)=>n+Number(e.successes||0),0),roll=1+Math.floor(Math.random()*20),total=roll+Number(t.current_rank||0)+Number(r.environment_modifier||0),success=total>=rules.dc,room=Math.max(0,3-used),award=success?Math.min(rules.award,room):0,mode=t.metadata?.mode||C.getChar(r.character_id)?.mode||C.getChar(r.character_id)?.payload?.mode||'exodo';let consequence='',risk={};if(!success&&r.training_type==='practical')consequence='Fadiga temporária: -1 em testes da capacidade até o próximo descanso ou desvantagem na próxima tentativa.';if(!success&&r.training_type==='difficult')consequence='Penalidade extensiva: -2 em testes relacionados por 1d4 dias ou aflição narrativa grave, a critério do Mestre.';if(award&&['power','ritual'].includes(t.capability_type)){t.metadata=t.metadata||{};t.metadata.discoveries=Number(t.metadata.discoveries||0)+1;t.metadata.last_discovery_at=C.now();t.metadata.mode=mode;t.updated_at=C.now()}if(!award&&!success&&['power','ritual'].includes(t.capability_type)){t.metadata=t.metadata||{};const count=Number(t.metadata.risk_count||0)+1;risk=riskProfile(mode,t.capability_type,r.training_type,count);t.metadata={...t.metadata,mode,risk_count:count,risk_theme:risk.theme,risk_label:risk.label,risk_severity:risk.severity,last_risk_consequence:[consequence,risk.consequence].filter(Boolean).join(' · '),last_risk_at:C.now(),risk_profile:risk};t.updated_at=C.now();consequence=t.metadata.last_risk_consequence}r.status='resolved';Object.assign(r,{roll,total,dc:rules.dc,success,awarded_successes:award,consequence});if(award)addSuccess(C,t,award,{eventType:'TRAINING_SUCCESS',session:r.session_label,note:r.note,metadata:{requestId:r.id,period,trainingType:r.training_type,roll,total,dc:rules.dc,environmentModifier:r.environment_modifier,mode}});else addEvent(C,{table_id:r.table_id,character_id:r.character_id,track_id:t.id,event_type:'TRAINING_FAILURE',successes:0,session_label:r.session_label,note:r.note,metadata:{requestId:r.id,period,trainingType:r.training_type,roll,total,dc:rules.dc,environmentModifier:r.environment_modifier,consequence,mode,riskCount:Number(t.metadata?.risk_count||0),riskProfile:risk}});C.save();return r}
  function localRequestUpgrade(C,a){const tableId=String(a.p_table_id),charId=String(a.p_character_id);if(!ownMember(C,tableId,charId))throw new Error('CHARACTER_MEMBERSHIP_REQUIRED');const t=findTrack(C,tableId,charId,a.p_capability_type,a.p_capability_key);if(!t)throw new Error('TRACK_NOT_FOUND');updateTrackStatus(t);if(t.status!=='ready')throw new Error('EVOLUTION_NOT_READY');const c=C.getChar(charId),acc=account(C,tableId,charId),target=Number(t.current_rank||0)+1,cost=costFor(c,t.capability_type,target);const p=ensureBuckets(C.state());if(p.upgradeRequests.some(x=>x.track_id===t.id&&x.status==='pending'))throw new Error('UPGRADE_ALREADY_PENDING');const r={id:C.id('upgrade'),table_id:tableId,character_id:charId,user_id:C.currentId(),track_id:t.id,capability_type:t.capability_type,capability_key:t.capability_key,label:t.label,from_rank:t.current_rank,to_rank:target,recommended_cost:cost,balance_at_request:Number(acc.balance||0),peg_shortfall:Math.max(0,cost-Number(acc.balance||0)),status:'pending',note:String(a.p_note||''),created_at:C.now()};p.upgradeRequests.unshift(r);C.save();return r}
  function applyUpgrade(C,r,cost,{acceleration=false,free=false,reason='' }={}){const p=ensureBuckets(C.state()),t=p.tracks[r.track_id]||findTrack(C,r.table_id,r.character_id,r.capability_type,r.capability_key);if(!t)throw new Error('TRACK_NOT_FOUND');updateTrackStatus(t);if(!acceleration&&t.status!=='ready')throw new Error('EVOLUTION_NOT_READY');if(!acceleration&&!allRequirementsDone(t))throw new Error('REQUIREMENTS_PENDING');const c=C.getChar(r.character_id),acc=account(C,r.table_id,r.character_id),target=Number(r.to_rank||Number(t.current_rank)+1),finalCost=Math.max(0,Number(cost??costFor(c,t.capability_type,target)));if(!free&&acc.balance<finalCost)throw new Error('INSUFFICIENT_CHARACTER_PROGRESSION');C.state().characterVersions?.push({id:C.id('ver'),character_id:c.id,version_no:(C.state().characterVersions||[]).filter(v=>v.character_id===c.id).length+1,payload:clone(c.payload),created_at:C.now()});applyTrackToCharacter(C,t,target);if(!free){acc.balance-=finalCost;acc.lifetime_spent=Number(acc.lifetime_spent||0)+finalCost;acc.updated_at=C.now()}t.current_rank=target;t.successes=0;t.successes_required=successRequired(target+1);if(resetsNarrativeRequirements(t.capability_type))t.requirements=(t.requirements||[]).map(x=>({...x,done:false}));t.status='progress';t.updated_at=C.now();C.tx({table_id:r.table_id,character_id:r.character_id,target_user_id:acc.user_id,amount:free?0:-finalCost,balance_after:acc.balance,tx_type:acceleration?'EVOLUTION_ACCELERATION':'SEMANTIC_EVOLUTION',reason:reason||`${t.label} ${target-1}→${target}`,metadata:{track_id:t.id,capability_type:t.capability_type,capability_key:t.capability_key,from:target-1,to:target,cost:finalCost,free}});addEvent(C,{table_id:r.table_id,character_id:r.character_id,track_id:t.id,event_type:acceleration?'ACCELERATION':'EVOLUTION_APPLIED',successes:0,note:reason||r.note||'',metadata:{from:target-1,to:target,cost:finalCost,free}});return{track:clone(t),character:clone(c),account:clone(acc),cost:finalCost}}
  function localResolveUpgrade(C,a){const p=ensureBuckets(C.state()),r=p.upgradeRequests.find(x=>x.id===String(a.p_request_id));if(!r||!manager(C,r.table_id))throw new Error('GM_REQUIRED');if(r.status!=='pending')return{request:r};r.decision_reason=String(a.p_reason||'');r.decided_at=C.now();if(!a.p_approved){r.status='rejected';C.save();return{request:r}}const result=applyUpgrade(C,r,a.p_final_cost,{reason:r.decision_reason});r.status='approved';r.final_cost=result.cost;C.save();return{request:clone(r),...result}}
  function localGrantUpgrade(C,a){const tableId=String(a.p_table_id),charId=String(a.p_character_id);if(!manager(C,tableId))throw new Error('GM_REQUIRED');const reason=String(a.p_reason||'').trim();if(!reason)throw new Error('REASON_REQUIRED');const t=findTrack(C,tableId,charId,a.p_capability_type,a.p_capability_key);if(!t)throw new Error('TRACK_NOT_FOUND');updateTrackStatus(t);if(t.status!=='ready')throw new Error('EVOLUTION_NOT_READY');const c=C.getChar(charId),acc=account(C,tableId,charId),target=Number(t.current_rank||0)+1,cost=costFor(c,t.capability_type,target),shortfall=Math.max(0,cost-Number(acc.balance||0));if(shortfall>0){if(!a.p_auto_fund_missing)throw new Error('INSUFFICIENT_CHARACTER_PROGRESSION');const wallet=C.ensureProgressionWallet(tableId);if(Number(wallet.balance||0)<shortfall)throw new Error('INSUFFICIENT_TABLE_PROGRESSION');wallet.balance=Number(wallet.balance||0)-shortfall;wallet.lifetime_distributed=Number(wallet.lifetime_distributed||0)+shortfall;wallet.updated_at=C.now();acc.balance=Number(acc.balance||0)+shortfall;acc.lifetime_granted=Number(acc.lifetime_granted||0)+shortfall;acc.updated_at=C.now();C.tx({table_id:tableId,character_id:charId,actor_id:C.currentId(),target_user_id:acc.user_id,amount:-shortfall,balance_after:wallet.balance,tx_type:'TABLE_GRANT_DEBIT',reason:`Complemento automático para evolução · ${reason}`,metadata:{character_id:charId,track_id:t.id,auto_fund:true}});C.tx({table_id:tableId,character_id:charId,actor_id:C.currentId(),target_user_id:acc.user_id,amount:shortfall,balance_after:acc.balance,tx_type:'CHARACTER_GRANT',reason:`Complemento automático para evolução · ${reason}`,metadata:{track_id:t.id,auto_fund:true}})}const result=applyUpgrade(C,{table_id:tableId,character_id:charId,track_id:t.id,capability_type:t.capability_type,capability_key:t.capability_key,label:t.label,from_rank:t.current_rank,to_rank:target,note:reason},cost,{reason});C.save();return{...result,funded_missing:shortfall}}
  function localResolveUpgradeFunded(C,a){const p=ensureBuckets(C.state()),r=p.upgradeRequests.find(x=>x.id===String(a.p_request_id));if(!r||!manager(C,r.table_id))throw new Error('GM_REQUIRED');if(r.status!=='pending')return{request:r};r.decision_reason=String(a.p_reason||'');r.decided_at=C.now();if(!a.p_approved){r.status='rejected';C.save();return{request:r}}const t=p.tracks[r.track_id]||findTrack(C,r.table_id,r.character_id,r.capability_type,r.capability_key);if(!t)throw new Error('TRACK_NOT_FOUND');const acc=account(C,r.table_id,r.character_id),cost=Math.max(0,Number(a.p_final_cost==null?r.recommended_cost:a.p_final_cost)),shortfall=Math.max(0,cost-Number(acc.balance||0));if(shortfall>0){if(!a.p_auto_fund_missing)throw new Error('INSUFFICIENT_CHARACTER_PROGRESSION');const wallet=C.ensureProgressionWallet(r.table_id);if(Number(wallet.balance||0)<shortfall)throw new Error('INSUFFICIENT_TABLE_PROGRESSION');wallet.balance=Number(wallet.balance||0)-shortfall;wallet.lifetime_distributed=Number(wallet.lifetime_distributed||0)+shortfall;wallet.updated_at=C.now();acc.balance=Number(acc.balance||0)+shortfall;acc.lifetime_granted=Number(acc.lifetime_granted||0)+shortfall;acc.updated_at=C.now();C.tx({table_id:r.table_id,character_id:r.character_id,actor_id:C.currentId(),target_user_id:acc.user_id,amount:-shortfall,balance_after:wallet.balance,tx_type:'TABLE_GRANT_DEBIT',reason:`Complemento automático para evolução · ${r.decision_reason||r.note||'Aprovação do Mestre'}`,metadata:{character_id:r.character_id,track_id:r.track_id,request_id:r.id,auto_fund:true}});C.tx({table_id:r.table_id,character_id:r.character_id,actor_id:C.currentId(),target_user_id:acc.user_id,amount:shortfall,balance_after:acc.balance,tx_type:'CHARACTER_GRANT',reason:`Complemento automático para evolução · ${r.decision_reason||r.note||'Aprovação do Mestre'}`,metadata:{track_id:r.track_id,request_id:r.id,auto_fund:true}})}const result=applyUpgrade(C,r,cost,{reason:r.decision_reason||r.note});r.status='approved';r.final_cost=result.cost;r.funded_missing=shortfall;C.save();return{request:clone(r),...result,funded_missing:shortfall}}
  function localAccelerate(C,a){const tableId=String(a.p_table_id),charId=String(a.p_character_id);if(!manager(C,tableId))throw new Error('GM_REQUIRED');const reason=String(a.p_reason||'').trim();if(!reason)throw new Error('REASON_REQUIRED');const t=findTrack(C,tableId,charId,a.p_capability_type,a.p_capability_key);if(!t)throw new Error('TRACK_NOT_FOUND');const r={table_id:tableId,character_id:charId,track_id:t.id,capability_type:t.capability_type,capability_key:t.capability_key,label:t.label,from_rank:t.current_rank,to_rank:Number(t.current_rank)+1,note:reason};const result=applyUpgrade(C,r,null,{acceleration:true,free:!!a.p_free,reason});C.save();return result}
  function localSetRequirement(C,a){const tableId=String(a.p_table_id),charId=String(a.p_character_id);if(!manager(C,tableId))throw new Error('GM_REQUIRED');const t=findTrack(C,tableId,charId,a.p_capability_type,a.p_capability_key);if(!t)throw new Error('TRACK_NOT_FOUND');const key=String(a.p_requirement_key||'').trim();if(!key)throw new Error('REQUIREMENT_REQUIRED');let req=(t.requirements||[]).find(x=>x.key===key);if(!req){req={key,label:String(a.p_label||key),done:false};(t.requirements||(t.requirements=[])).push(req)}req.done=!!a.p_done;if(a.p_label)req.label=String(a.p_label);updateTrackStatus(t);addEvent(C,{table_id:tableId,character_id:charId,track_id:t.id,event_type:'REQUIREMENT_UPDATED',note:req.label,metadata:{requirement:key,done:req.done}});C.save();return clone(t)}
  function localSubmitDevelopment(C,a){const tableId=String(a.p_table_id),charId=String(a.p_character_id);if(!ownMember(C,tableId,charId))throw new Error('CHARACTER_MEMBERSHIP_REQUIRED');const focus=['power','skill','class'].includes(typeMap(a.p_focus_type))?typeMap(a.p_focus_type):'power',cost=Number(a.p_requested_cost||0);if(cost<=0)throw new Error('COST_AND_NOTE_REQUIRED');const p=ensureBuckets(C.state()),r={id:C.id('dev'),table_id:tableId,character_id:charId,user_id:C.currentId(),proposed_payload:clone(a.p_payload||{}),requested_cost:cost,note:String(a.p_note||''),proposal_kind:'development',focus_type:focus,status:'pending',created_at:C.now()};p.proposals.unshift(r);C.save();return r}
  function localResolveDevelopment(C,a){const p=ensureBuckets(C.state()),r=p.proposals.find(x=>x.id===String(a.p_request_id)&&x.proposal_kind==='development');if(!r||!manager(C,r.table_id))throw new Error('GM_REQUIRED');if(r.status!=='pending')return r;r.decided_at=C.now();r.decision_reason=String(a.p_reason||'');if(!a.p_approved){r.status='rejected';C.save();return r}const c=C.getChar(r.character_id),acc=account(C,r.table_id,r.character_id),cost=Math.max(0,Number(a.p_final_cost??r.requested_cost));if(acc.balance<cost)throw new Error('INSUFFICIENT_CHARACTER_PROGRESSION');C.state().characterVersions?.push({id:C.id('ver'),character_id:c.id,version_no:(C.state().characterVersions||[]).filter(v=>v.character_id===c.id).length+1,payload:clone(c.payload),created_at:C.now()});const src=r.proposed_payload||{},dst=c.payload||{};if(r.focus_type==='power'){dst.powers=clone(src.powers||dst.powers||[]);dst.powersHtml=clone(src.powersHtml||dst.powersHtml||[]);dst.rituals=clone(src.rituals||dst.rituals||[])}else if(r.focus_type==='skill'){dst.skills=clone(src.skills||parseLegacySkills(src));dst.skillsHtml=clone(src.skillsHtml||dst.skillsHtml||[])}else{dst.progression={...(dst.progression||{}),...(src.progression||{})};dst.className=src.className||dst.className;c.class_name=dst.className||c.class_name}dst.progression={...(dst.progression||{}),lastTableId:r.table_id,lastEvolutionAt:C.now()};c.payload=dst;c.updated_at=C.now();acc.balance-=cost;acc.lifetime_spent=Number(acc.lifetime_spent||0)+cost;C.tx({table_id:r.table_id,character_id:r.character_id,target_user_id:acc.user_id,amount:-cost,balance_after:acc.balance,tx_type:'DEVELOPMENT_APPROVED',reason:r.decision_reason||r.note,reference_id:r.id,metadata:{focus_type:r.focus_type}});addEvent(C,{table_id:r.table_id,character_id:r.character_id,event_type:'DEVELOPMENT_APPROVED',note:r.decision_reason||r.note,metadata:{focus_type:r.focus_type,cost}});r.status='approved';r.final_cost=cost;ensureCharacterTracks(C,r.table_id,r.character_id);C.save();return r}
  const localHandlers={
    progression_character_evolution_state:localState,
    progression_submit_evidence:localSubmitEvidence,
    progression_resolve_evidence:localResolveEvidence,
    progression_record_track_success:localRecordSuccess,
    progression_request_training:localRequestTraining,
    progression_resolve_training:localResolveTraining,
    progression_request_semantic_upgrade:localRequestUpgrade,
    progression_resolve_semantic_upgrade:localResolveUpgrade,
    progression_resolve_semantic_upgrade_v2:localResolveUpgradeFunded,
    progression_grant_semantic_upgrade:localGrantUpgrade,
    progression_accelerate_track:localAccelerate,
    progression_set_track_requirement:localSetRequirement,
    progression_submit_development:localSubmitDevelopment,
    progression_resolve_development:localResolveDevelopment
  };
  async function rpc(name,args={}){
    const C=ctx();
    if(C){try{const fn=localHandlers[name];if(!fn)throw new Error(`OFFLINE_RPC_NOT_IMPLEMENTED:${name}`);return clone(await fn(C,args||{}))}catch(error){throw error}}
    const result=await db()?.rpc?.(name,args||{});if(result?.error)throw result.error;return result?.data!==undefined?result.data:result;
  }
  function extendOfflineState(tableId,base){
    const C=ctx();if(!C)return base;const p=ensureBuckets(C.state()),managed=C.canManage(tableId);if(!managed)return base;for(const m of (C.state().members||[]).filter(x=>x.table_id===String(tableId)&&x.status==='active'&&x.character_id)){C.ensureProgressionAccount(String(tableId),String(m.character_id));ensureCharacterTracks(C,tableId,m.character_id)}const tracks=Object.values(p.tracks).filter(x=>x.table_id===String(tableId)),byChar={};for(const t of tracks)(byChar[t.character_id]||(byChar[t.character_id]=[])).push(t);return{...base,tracks:clone(tracks),tracksByCharacter:clone(byChar),evidenceRequests:clone(p.evidenceRequests.filter(x=>x.table_id===String(tableId)&&x.status==='pending')),trainingRequests:clone(p.trainingRequests.filter(x=>x.table_id===String(tableId)&&x.status==='pending')),upgradeRequests:clone(p.upgradeRequests.filter(x=>x.table_id===String(tableId)&&x.status==='pending')),developmentRequests:clone(p.proposals.filter(x=>x.table_id===String(tableId)&&x.status==='pending'&&x.proposal_kind==='development')),evolutionEvents:clone(p.events.filter(x=>x.table_id===String(tableId)).slice(0,60))}}
  const api=Object.freeze({
    version:'2.10.1',rpc,extendOfflineState,typeMap,typeLabel,slug,successRequired,costFor,requirementsFor,riskProfile,
    state:(tableId,characterId)=>rpc('progression_character_evolution_state',{p_table_id:String(tableId),p_character_id:String(characterId)}),
    submitEvidence:(tableId,characterId,type,key,successes,session,note)=>rpc('progression_submit_evidence',{p_table_id:String(tableId),p_character_id:String(characterId),p_capability_type:typeMap(type),p_capability_key:String(key),p_successes:Number(successes||1),p_session_label:String(session||''),p_note:String(note||'')}),
    resolveEvidence:(requestId,approved,reason='')=>rpc('progression_resolve_evidence',{p_request_id:String(requestId),p_approved:!!approved,p_reason:String(reason||'')}),
    recordSuccess:(tableId,characterId,type,key,successes,session,note)=>rpc('progression_record_track_success',{p_table_id:String(tableId),p_character_id:String(characterId),p_capability_type:typeMap(type),p_capability_key:String(key),p_successes:Number(successes||1),p_session_label:String(session||''),p_note:String(note||'')}),
    requestTraining:(tableId,characterId,type,key,trainingType,environmentModifier,session,note)=>rpc('progression_request_training',{p_table_id:String(tableId),p_character_id:String(characterId),p_capability_type:typeMap(type),p_capability_key:String(key),p_training_type:String(trainingType||'practical'),p_environment_modifier:Number(environmentModifier||0),p_session_label:String(session||''),p_note:String(note||'')}),
    resolveTraining:(requestId,approved,reason='')=>rpc('progression_resolve_training',{p_request_id:String(requestId),p_approved:!!approved,p_reason:String(reason||'')}),
    requestUpgrade:(tableId,characterId,type,key,note='')=>rpc('progression_request_semantic_upgrade',{p_table_id:String(tableId),p_character_id:String(characterId),p_capability_type:typeMap(type),p_capability_key:String(key),p_note:String(note||'')}),
    resolveUpgrade:(requestId,approved,finalCost=null,reason='',autoFundMissing=false)=>rpc('progression_resolve_semantic_upgrade_v2',{p_request_id:String(requestId),p_approved:!!approved,p_final_cost:finalCost==null?null:Number(finalCost),p_reason:String(reason||''),p_auto_fund_missing:!!autoFundMissing}),
    grantUpgrade:(tableId,characterId,type,key,autoFundMissing=false,reason='')=>rpc('progression_grant_semantic_upgrade',{p_table_id:String(tableId),p_character_id:String(characterId),p_capability_type:typeMap(type),p_capability_key:String(key),p_auto_fund_missing:!!autoFundMissing,p_reason:String(reason||'')}),
    accelerate:(tableId,characterId,type,key,free,reason)=>rpc('progression_accelerate_track',{p_table_id:String(tableId),p_character_id:String(characterId),p_capability_type:typeMap(type),p_capability_key:String(key),p_free:!!free,p_reason:String(reason||'')}),
    setRequirement:(tableId,characterId,type,key,requirementKey,done,label='')=>rpc('progression_set_track_requirement',{p_table_id:String(tableId),p_character_id:String(characterId),p_capability_type:typeMap(type),p_capability_key:String(key),p_requirement_key:String(requirementKey),p_done:!!done,p_label:String(label||'')}),
    submitDevelopment:(tableId,characterId,focusType,payload,requestedCost,note)=>rpc('progression_submit_development',{p_table_id:String(tableId),p_character_id:String(characterId),p_focus_type:typeMap(focusType),p_payload:payload||{},p_requested_cost:Number(requestedCost||0),p_note:String(note||'')}),
    resolveDevelopment:(requestId,approved,finalCost=null,reason='')=>rpc('progression_resolve_development',{p_request_id:String(requestId),p_approved:!!approved,p_final_cost:finalCost==null?null:Number(finalCost),p_reason:String(reason||'')})
  });
  window.MS_EVOLUTION_BACKEND=api;
})();
